"""The PiPup integration: popups on Android TV via the PiPup fork.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from datetime import timedelta

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant
from homeassistant.helpers import device_registry as dr, entity_registry as er
from homeassistant.helpers.typing import ConfigType

from .const import (  # noqa: F401
    CONF_NAME_SUFFIX,
    CONF_NAME_SUFFIX_APPLIED,
    CONF_SCAN_INTERVAL,
    DEFAULT_SCAN_INTERVAL,
    DOMAIN,
)
from .coordinator import PiPupCoordinator
from .services import async_setup_services

PLATFORMS: list[Platform] = [
    Platform.BINARY_SENSOR,
    Platform.BUTTON,
    Platform.NOTIFY,
    Platform.SELECT,
    Platform.SENSOR,
    Platform.UPDATE,
]

type PiPupConfigEntry = ConfigEntry[PiPupCoordinator]


async def async_setup(hass: HomeAssistant, config: ConfigType) -> bool:
    """Register domain-wide actions."""
    await async_setup_services(hass)
    return True


async def async_setup_entry(hass: HomeAssistant, entry: PiPupConfigEntry) -> bool:
    """Set up a PiPup device from a config entry."""
    coordinator = PiPupCoordinator(hass, entry)
    await coordinator.async_config_entry_first_refresh()

    # app >= 0.2.5 reports a stable device id: adopt it as the entry unique_id
    # (must happen before the platforms build their entity unique_ids)
    _async_migrate_unique_id(hass, entry, coordinator.data.get("id"))

    entry.runtime_data = coordinator

    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

    _async_apply_name_suffix(hass, entry)

    entry.async_on_unload(entry.add_update_listener(_async_update_listener))
    return True


def _async_migrate_unique_id(
    hass: HomeAssistant, entry: ConfigEntry, device_id: str | None
) -> None:
    """Move the entry from a host:port unique_id to the device's stable id.

    Entity unique_ids and the device registry identifier are prefixed with the
    entry unique_id, so those must migrate along or every entity would be
    orphaned and recreated.
    """
    old = entry.unique_id or entry.entry_id
    if not device_id or entry.unique_id == device_id:
        return
    for other in hass.config_entries.async_entries(DOMAIN):
        if other.entry_id != entry.entry_id and other.unique_id == device_id:
            return  # would collide; leave the old unique_id in place

    ent_reg = er.async_get(hass)
    for entity in er.async_entries_for_config_entry(ent_reg, entry.entry_id):
        if entity.unique_id.startswith(f"{old}_"):
            ent_reg.async_update_entity(
                entity.entity_id,
                new_unique_id=f"{device_id}_{entity.unique_id[len(old) + 1:]}",
            )

    dev_reg = dr.async_get(hass)
    if device := dev_reg.async_get_device(identifiers={(DOMAIN, old)}):
        dev_reg.async_update_device(device.id, new_identifiers={(DOMAIN, device_id)})

    hass.config_entries.async_update_entry(entry, unique_id=device_id)


def _async_apply_name_suffix(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Append the configured suffix to the entity names in the registry.

    Turns e.g. "Popup" into "Popup Veranda" so multiple PiPup devices stay
    distinguishable in target pickers. Only names we set ourselves (or unset
    names) are touched — manual renames by the user are left alone. Clearing
    the suffix removes our names again.
    """
    suffix = (entry.options.get(CONF_NAME_SUFFIX) or "").strip()
    applied = entry.options.get(CONF_NAME_SUFFIX_APPLIED) or ""

    registry = er.async_get(hass)
    for entity in er.async_entries_for_config_entry(registry, entry.entry_id):
        base = entity.original_name
        if not base:
            continue
        ours = f"{base} {applied}" if applied else None
        if suffix:
            new_name = f"{base} {suffix}"
            if (entity.name is None or entity.name == ours) and entity.name != new_name:
                registry.async_update_entity(entity.entity_id, name=new_name)
        elif ours and entity.name == ours:
            registry.async_update_entity(entity.entity_id, name=None)

    if applied != suffix:
        hass.config_entries.async_update_entry(
            entry, options={**entry.options, CONF_NAME_SUFFIX_APPLIED: suffix}
        )


async def _async_update_listener(hass: HomeAssistant, entry: PiPupConfigEntry) -> None:
    """Reload when the polling interval changed.

    Other option changes (e.g. the default-position select) apply at
    call time and don't need a reload.
    """
    _async_apply_name_suffix(hass, entry)

    coordinator = entry.runtime_data
    scan_interval = entry.options.get(CONF_SCAN_INTERVAL)
    desired = (
        timedelta(seconds=scan_interval) if scan_interval else DEFAULT_SCAN_INTERVAL
    )
    if coordinator.update_interval != desired:
        await hass.config_entries.async_reload(entry.entry_id)


async def async_unload_entry(hass: HomeAssistant, entry: PiPupConfigEntry) -> bool:
    """Unload a config entry."""
    return await hass.config_entries.async_unload_platforms(entry, PLATFORMS)
