"""The PiPup integration: popups on Android TV via the PiPup fork.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from datetime import timedelta

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant
from homeassistant.helpers.typing import ConfigType

from .const import CONF_SCAN_INTERVAL, DEFAULT_SCAN_INTERVAL, DOMAIN  # noqa: F401
from .coordinator import PiPupCoordinator
from .services import async_setup_services

PLATFORMS: list[Platform] = [
    Platform.BINARY_SENSOR,
    Platform.BUTTON,
    Platform.SELECT,
    Platform.SENSOR,
    Platform.UPDATE,
]

type PiPupConfigEntry = ConfigEntry[PiPupCoordinator]


async def async_setup(hass: HomeAssistant, config: ConfigType) -> bool:
    """Register domain-wide actions."""
    await async_setup_services(hass)
    return True


async def async_setup_entry(hass: HomeAssistant, entry: PiPupConfigEntry) -> bool:
    """Set up a PiPup device from a config entry."""
    coordinator = PiPupCoordinator(hass, entry)
    await coordinator.async_config_entry_first_refresh()

    entry.runtime_data = coordinator

    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

    entry.async_on_unload(entry.add_update_listener(_async_update_listener))
    return True


async def _async_update_listener(hass: HomeAssistant, entry: PiPupConfigEntry) -> None:
    """Reload when the polling interval changed.

    Other option changes (e.g. the default-position select) apply at
    call time and don't need a reload.
    """
    coordinator = entry.runtime_data
    scan_interval = entry.options.get(CONF_SCAN_INTERVAL)
    desired = (
        timedelta(seconds=scan_interval) if scan_interval else DEFAULT_SCAN_INTERVAL
    )
    if coordinator.update_interval != desired:
        await hass.config_entries.async_reload(entry.entry_id)


async def async_unload_entry(hass: HomeAssistant, entry: PiPupConfigEntry) -> bool:
    """Unload a config entry."""
    return await hass.config_entries.async_unload_platforms(entry, PLATFORMS)
