"""Thin async client for the PiPup HTTP API (fork with /state support).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from typing import Any

import aiohttp


class PiPupError(Exception):
    """Communication error with the PiPup device."""


class PiPupUnsupportedError(PiPupError):
    """Device responds but does not support the fork API (/state)."""


class PiPupClient:
    """Async client for a single PiPup device."""

    def __init__(self, session: aiohttp.ClientSession, host: str, port: int) -> None:
        """Initialize the client."""
        self._session = session
        self._base = f"http://{host}:{port}"
        self.host = host
        self.port = port

    async def state(self) -> dict[str, Any]:
        """Fetch /state from the device."""
        try:
            async with self._session.get(
                f"{self._base}/state", timeout=aiohttp.ClientTimeout(total=10)
            ) as resp:
                if resp.status == 400:
                    # Upstream PiPup without the fork additions answers
                    # "invalid request" on unknown URIs/methods.
                    raise PiPupUnsupportedError(
                        "PiPup fork with /state support required"
                    )
                resp.raise_for_status()
                return await resp.json(content_type=None)
        except PiPupError:
            raise
        except (aiohttp.ClientError, TimeoutError) as err:
            raise PiPupError(f"Cannot reach PiPup at {self._base}: {err}") from err

    async def notify(self, payload: dict[str, Any]) -> None:
        """Show a popup."""
        try:
            async with self._session.post(
                f"{self._base}/notify",
                json=payload,
                timeout=aiohttp.ClientTimeout(total=10),
            ) as resp:
                if resp.status != 200:
                    body = await resp.text()
                    raise PiPupError(f"notify failed ({resp.status}): {body}")
        except PiPupError:
            raise
        except (aiohttp.ClientError, TimeoutError) as err:
            raise PiPupError(f"Cannot reach PiPup at {self._base}: {err}") from err

    async def notify_image(self, fields: dict[str, str], image: bytes) -> None:
        """Show a popup with an uploaded snapshot image (multipart)."""
        form = aiohttp.FormData()
        for key, value in fields.items():
            form.add_field(key, value)
        form.add_field(
            "image", image, filename="snapshot.jpg", content_type="image/jpeg"
        )
        try:
            async with self._session.post(
                f"{self._base}/notify",
                data=form,
                timeout=aiohttp.ClientTimeout(total=15),
            ) as resp:
                if resp.status != 200:
                    body = await resp.text()
                    raise PiPupError(f"notify failed ({resp.status}): {body}")
        except PiPupError:
            raise
        except (aiohttp.ClientError, TimeoutError) as err:
            raise PiPupError(f"Cannot reach PiPup at {self._base}: {err}") from err

    async def update_app(self) -> None:
        """Ask the app to download and install the latest release (app >= 0.6.0).

        Returns as soon as the device accepted the request: the install itself
        runs on the TV and its progress shows up in /state.
        """
        try:
            async with self._session.post(
                f"{self._base}/update", timeout=aiohttp.ClientTimeout(total=15)
            ) as resp:
                if resp.status == 400:
                    raise PiPupUnsupportedError(
                        "this PiPup version has no self-update (needs app >= 0.6.0)"
                    )
                if resp.status != 200:
                    body = await resp.text()
                    raise PiPupError(f"update failed ({resp.status}): {body}")
        except PiPupError:
            raise
        except (aiohttp.ClientError, TimeoutError) as err:
            raise PiPupError(f"Cannot reach PiPup at {self._base}: {err}") from err

    async def power(self, state: str) -> dict[str, Any]:
        """Turn the device's screen on or off (app >= 0.7.0).

        The app answers 501 when it has no granted way to turn the screen off
        (no device admin, no accessibility service) and 400 when it predates
        /power entirely - both surface as PiPupUnsupportedError, so the caller
        can tell "this device cannot" apart from a network failure.
        """
        try:
            async with self._session.post(
                f"{self._base}/power",
                params={"state": state},
                timeout=aiohttp.ClientTimeout(total=10),
            ) as resp:
                if resp.status in (400, 501):
                    body = await resp.text()
                    raise PiPupUnsupportedError(
                        f"device cannot switch its screen {state}: {body}"
                    )
                if resp.status != 200:
                    body = await resp.text()
                    raise PiPupError(f"power failed ({resp.status}): {body}")
                return await resp.json(content_type=None)
        except PiPupError:
            raise
        except (aiohttp.ClientError, TimeoutError) as err:
            raise PiPupError(f"Cannot reach PiPup at {self._base}: {err}") from err

    async def fix_permission(self, what: str | None = None) -> dict[str, Any]:
        """Ask the TV to put a permission screen in front of the user (app >= 0.8.0).

        `what` picks a specific permission, "next" the first missing one; omitted opens
        PiPup's own status screen, which lists them all with their own buttons. The app
        answers 501 when this device has no such screen - Fire OS resolves those intents
        to do-nothing placeholders - and its reply then carries the adb command instead.
        """
        params = {"what": what} if what else None
        try:
            async with self._session.post(
                f"{self._base}/permissions/fix",
                params=params,
                timeout=aiohttp.ClientTimeout(total=15),
            ) as resp:
                if resp.status in (400, 501):
                    body = await resp.json(content_type=None)
                    raise PiPupUnsupportedError(
                        body.get("adb")
                        or f"this device cannot open that screen ({resp.status})"
                    )
                if resp.status != 200:
                    body = await resp.text()
                    raise PiPupError(f"permission fix failed ({resp.status}): {body}")
                return await resp.json(content_type=None)
        except PiPupError:
            raise
        except (aiohttp.ClientError, TimeoutError) as err:
            raise PiPupError(f"Cannot reach PiPup at {self._base}: {err}") from err

    async def cancel(self, popup_id: str | None = None) -> None:
        """Dismiss the current popup, optionally only when popup_id matches."""
        params = {"id": popup_id} if popup_id else None
        try:
            async with self._session.post(
                f"{self._base}/cancel",
                params=params,
                timeout=aiohttp.ClientTimeout(total=10),
            ) as resp:
                if resp.status != 200:
                    body = await resp.text()
                    raise PiPupError(f"cancel failed ({resp.status}): {body}")
        except PiPupError:
            raise
        except (aiohttp.ClientError, TimeoutError) as err:
            raise PiPupError(f"Cannot reach PiPup at {self._base}: {err}") from err
