"""Binary sensors: popup visible, screen on.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from typing import Any

from homeassistant.components.binary_sensor import (
    BinarySensorDeviceClass,
    BinarySensorEntity,
)
from homeassistant.const import EntityCategory
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from .coordinator import PiPupCoordinator
from .entity import PiPupEntity


async def async_setup_entry(
    hass: HomeAssistant,
    entry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the PiPup binary sensors."""
    coordinator: PiPupCoordinator = entry.runtime_data
    entities = [
        PiPupPopupSensor(coordinator, entry),
        PiPupConnectivitySensor(coordinator, entry),
    ]
    # Needs the fork app >= 0.2.3.
    if "screenOn" in coordinator.data:
        entities.append(PiPupScreenSensor(coordinator, entry))
    async_add_entities(entities)


class PiPupPopupSensor(PiPupEntity, BinarySensorEntity):
    """On when a popup is visible on the device."""

    _attr_translation_key = "popup"

    def __init__(self, coordinator: PiPupCoordinator, entry) -> None:
        """Initialize the sensor."""
        super().__init__(coordinator, entry, "popup")

    @property
    def is_on(self) -> bool | None:
        """Return True when a popup is visible; unknown when unreachable."""
        if not self.coordinator.online:
            return None
        return bool(self.coordinator.data.get("visible"))

    @property
    def extra_state_attributes(self) -> dict[str, Any] | None:
        """Expose popup details (id, duration, elapsed seconds)."""
        popup = self.coordinator.data.get("popup")
        if not popup:
            return None
        return {
            "popup_id": popup.get("id"),
            "duration": popup.get("duration"),
            "indefinite": popup.get("indefinite"),
            "elapsed": popup.get("elapsed"),
        }


class PiPupScreenSensor(PiPupEntity, BinarySensorEntity):
    """On when the TV screen is on/interactive."""

    _attr_translation_key = "screen"
    _attr_device_class = BinarySensorDeviceClass.POWER

    def __init__(self, coordinator: PiPupCoordinator, entry) -> None:
        """Initialize the sensor."""
        super().__init__(coordinator, entry, "screen")

    @property
    def is_on(self) -> bool | None:
        """Return True when the screen is interactive; unknown when unreachable."""
        if not self.coordinator.online:
            return None
        value = self.coordinator.data.get("screenOn")
        return bool(value) if value is not None else None


class PiPupConnectivitySensor(PiPupEntity, BinarySensorEntity):
    """On when the PiPup server on the TV answers /state polls.

    FireTV sticks cut their network in standby, so this doubles as a
    wake/sleep signal — automate on the off→on edge instead of on
    entities becoming unavailable.
    """

    _attr_translation_key = "connectivity"
    _attr_device_class = BinarySensorDeviceClass.CONNECTIVITY
    _attr_entity_category = EntityCategory.DIAGNOSTIC

    def __init__(self, coordinator: PiPupCoordinator, entry) -> None:
        """Initialize the sensor."""
        super().__init__(coordinator, entry, "connectivity")

    @property
    def is_on(self) -> bool:
        """Return True when the device answered the last poll."""
        return self.coordinator.online
