"""Binary sensor: is a popup currently visible on the TV.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from typing import Any

from homeassistant.components.binary_sensor import BinarySensorEntity
from homeassistant.core import HomeAssistant
from homeassistant.helpers.device_registry import DeviceInfo
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .const import DOMAIN
from .coordinator import PiPupCoordinator


async def async_setup_entry(
    hass: HomeAssistant,
    entry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the popup binary sensor."""
    coordinator: PiPupCoordinator = entry.runtime_data
    async_add_entities([PiPupPopupSensor(coordinator, entry)])


class PiPupPopupSensor(CoordinatorEntity[PiPupCoordinator], BinarySensorEntity):
    """On when a popup is visible on the device."""

    _attr_has_entity_name = True
    _attr_translation_key = "popup"

    def __init__(self, coordinator: PiPupCoordinator, entry) -> None:
        """Initialize the sensor."""
        super().__init__(coordinator)
        self._attr_unique_id = f"{entry.unique_id or entry.entry_id}_popup"
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, entry.unique_id or entry.entry_id)},
            name=entry.title,
            manufacturer="PiPup (fork)",
            model="Android TV popup service",
            sw_version=coordinator.data.get("version"),
            configuration_url=(
                f"http://{coordinator.client.host}:{coordinator.client.port}/state"
            ),
        )

    @property
    def is_on(self) -> bool:
        """Return True when a popup is visible."""
        return bool(self.coordinator.data.get("visible"))

    @property
    def extra_state_attributes(self) -> dict[str, Any] | None:
        """Expose popup details (id, duration, elapsed seconds)."""
        popup = self.coordinator.data.get("popup")
        if not popup:
            return None
        return {
            "popup_id": popup.get("id"),
            "duration": popup.get("duration"),
            "indefinite": popup.get("indefinite"),
            "elapsed": popup.get("elapsed"),
        }
