"""Button: dismiss the visible popup.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from homeassistant.components.button import ButtonEntity
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from .api import PiPupError
from .coordinator import PiPupCoordinator
from .entity import PiPupEntity


async def async_setup_entry(
    hass: HomeAssistant,
    entry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the dismiss button."""
    coordinator: PiPupCoordinator = entry.runtime_data
    async_add_entities([PiPupDismissButton(coordinator, entry)])


class PiPupDismissButton(PiPupEntity, ButtonEntity):
    """Dismisses whatever popup is visible."""

    _attr_translation_key = "dismiss"

    def __init__(self, coordinator: PiPupCoordinator, entry) -> None:
        """Initialize the button."""
        super().__init__(coordinator, entry, "dismiss")

    async def async_press(self) -> None:
        """Dismiss the current popup."""
        try:
            await self.coordinator.client.cancel()
        except PiPupError as err:
            raise HomeAssistantError(str(err)) from err
        await self.coordinator.async_refresh_soon()
