"""Config flow for the PiPup integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from typing import Any

import voluptuous as vol

from homeassistant.config_entries import (
    ConfigEntry,
    ConfigFlow,
    ConfigFlowResult,
    OptionsFlow,
)
from homeassistant.const import CONF_HOST, CONF_NAME, CONF_PORT
from homeassistant.core import callback
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .api import PiPupClient, PiPupError, PiPupUnsupportedError
from .const import (
    CONF_DEFAULT_BACKGROUND_COLOR,
    CONF_DEFAULT_DURATION,
    CONF_DEFAULT_MEDIA_HEIGHT,
    CONF_DEFAULT_MEDIA_WIDTH,
    CONF_DEFAULT_MESSAGE_COLOR,
    CONF_DEFAULT_MESSAGE_SIZE,
    CONF_DEFAULT_MUTED,
    CONF_DEFAULT_POSITION,
    CONF_DEFAULT_TITLE_COLOR,
    CONF_DEFAULT_TITLE_SIZE,
    CONF_NAME_SUFFIX,
    CONF_SCAN_INTERVAL,
    DEFAULT_PORT,
    DEFAULT_POSITION,
    DOMAIN,
    POSITIONS,
)

STEP_USER_SCHEMA = vol.Schema(
    {
        vol.Required(CONF_HOST): str,
        vol.Required(CONF_PORT, default=DEFAULT_PORT): vol.All(
            vol.Coerce(int), vol.Range(min=1, max=65535)
        ),
        vol.Optional(CONF_NAME): str,
        vol.Optional(CONF_NAME_SUFFIX): str,
    }
)


class PiPupConfigFlow(ConfigFlow, domain=DOMAIN):
    """Handle a config flow for PiPup."""

    VERSION = 1

    async def async_step_user(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Handle the initial step."""
        errors: dict[str, str] = {}

        if user_input is not None:
            host = user_input[CONF_HOST].strip()
            port = user_input[CONF_PORT]

            await self.async_set_unique_id(f"{host}:{port}")
            self._abort_if_unique_id_configured()

            client = PiPupClient(async_get_clientsession(self.hass), host, port)
            try:
                state = await client.state()
            except PiPupUnsupportedError:
                errors["base"] = "unsupported_version"
            except PiPupError:
                errors["base"] = "cannot_connect"
            else:
                title = user_input.get(CONF_NAME) or f"PiPup {host}"
                options = {}
                if suffix := (user_input.get(CONF_NAME_SUFFIX) or "").strip():
                    options[CONF_NAME_SUFFIX] = suffix
                return self.async_create_entry(
                    title=title,
                    data={CONF_HOST: host, CONF_PORT: port},
                    options=options,
                    description_placeholders={
                        "version": state.get("version", "?")
                    },
                )

        return self.async_show_form(
            step_id="user", data_schema=STEP_USER_SCHEMA, errors=errors
        )

    @staticmethod
    @callback
    def async_get_options_flow(config_entry: ConfigEntry) -> OptionsFlow:
        """Create the options flow."""
        return PiPupOptionsFlow()


class PiPupOptionsFlow(OptionsFlow):
    """Options flow: polling, entity names and per-device popup defaults."""

    async def async_step_init(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Manage the options."""
        if user_input is not None:
            # merge into the existing options: keys not in this form
            # (applied-suffix marker) must survive
            options = dict(self.config_entry.options)
            options[CONF_SCAN_INTERVAL] = user_input.get(CONF_SCAN_INTERVAL, 15)
            options[CONF_NAME_SUFFIX] = (
                user_input.get(CONF_NAME_SUFFIX) or ""
            ).strip()
            options[CONF_DEFAULT_POSITION] = user_input.get(
                CONF_DEFAULT_POSITION, DEFAULT_POSITION
            )
            options[CONF_DEFAULT_DURATION] = user_input.get(
                CONF_DEFAULT_DURATION, 30
            )
            options[CONF_DEFAULT_MUTED] = user_input.get(CONF_DEFAULT_MUTED, True)
            options[CONF_DEFAULT_MEDIA_WIDTH] = user_input.get(
                CONF_DEFAULT_MEDIA_WIDTH, 640
            )
            options[CONF_DEFAULT_MEDIA_HEIGHT] = user_input.get(
                CONF_DEFAULT_MEDIA_HEIGHT, 360
            )
            options[CONF_DEFAULT_TITLE_SIZE] = user_input.get(
                CONF_DEFAULT_TITLE_SIZE, 0
            )
            options[CONF_DEFAULT_MESSAGE_SIZE] = user_input.get(
                CONF_DEFAULT_MESSAGE_SIZE, 0
            )
            # colors: empty = no default (app decides)
            for key in (
                CONF_DEFAULT_TITLE_COLOR,
                CONF_DEFAULT_MESSAGE_COLOR,
                CONF_DEFAULT_BACKGROUND_COLOR,
            ):
                value = (user_input.get(key) or "").strip()
                if value:
                    options[key] = value
                else:
                    options.pop(key, None)
            return self.async_create_entry(title="", data=options)

        opts = self.config_entry.options
        return self.async_show_form(
            step_id="init",
            data_schema=vol.Schema(
                {
                    vol.Optional(
                        CONF_SCAN_INTERVAL,
                        default=opts.get(CONF_SCAN_INTERVAL, 15),
                    ): vol.All(vol.Coerce(int), vol.Range(min=5, max=300)),
                    vol.Optional(
                        CONF_NAME_SUFFIX,
                        description={
                            "suggested_value": opts.get(CONF_NAME_SUFFIX, "")
                        },
                    ): str,
                    vol.Optional(
                        CONF_DEFAULT_POSITION,
                        default=opts.get(CONF_DEFAULT_POSITION, DEFAULT_POSITION),
                    ): vol.In(list(POSITIONS)),
                    vol.Optional(
                        CONF_DEFAULT_DURATION,
                        default=opts.get(CONF_DEFAULT_DURATION, 30),
                    ): vol.All(vol.Coerce(int), vol.Range(min=0, max=86400)),
                    vol.Optional(
                        CONF_DEFAULT_MUTED,
                        default=opts.get(CONF_DEFAULT_MUTED, True),
                    ): bool,
                    vol.Optional(
                        CONF_DEFAULT_MEDIA_WIDTH,
                        default=opts.get(CONF_DEFAULT_MEDIA_WIDTH, 640),
                    ): vol.All(vol.Coerce(int), vol.Range(min=1, max=3840)),
                    vol.Optional(
                        CONF_DEFAULT_MEDIA_HEIGHT,
                        default=opts.get(CONF_DEFAULT_MEDIA_HEIGHT, 360),
                    ): vol.All(vol.Coerce(int), vol.Range(min=1, max=2160)),
                    vol.Optional(
                        CONF_DEFAULT_TITLE_SIZE,
                        default=opts.get(CONF_DEFAULT_TITLE_SIZE, 0),
                    ): vol.All(vol.Coerce(float), vol.Range(min=0, max=96)),
                    vol.Optional(
                        CONF_DEFAULT_MESSAGE_SIZE,
                        default=opts.get(CONF_DEFAULT_MESSAGE_SIZE, 0),
                    ): vol.All(vol.Coerce(float), vol.Range(min=0, max=96)),
                    vol.Optional(
                        CONF_DEFAULT_TITLE_COLOR,
                        description={
                            "suggested_value": opts.get(CONF_DEFAULT_TITLE_COLOR, "")
                        },
                    ): str,
                    vol.Optional(
                        CONF_DEFAULT_MESSAGE_COLOR,
                        description={
                            "suggested_value": opts.get(
                                CONF_DEFAULT_MESSAGE_COLOR, ""
                            )
                        },
                    ): str,
                    vol.Optional(
                        CONF_DEFAULT_BACKGROUND_COLOR,
                        description={
                            "suggested_value": opts.get(
                                CONF_DEFAULT_BACKGROUND_COLOR, ""
                            )
                        },
                    ): str,
                }
            ),
        )
