"""Constants for the PiPup integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from datetime import timedelta
from typing import Final

DOMAIN: Final = "pipup"

DEFAULT_PORT: Final = 7979
DEFAULT_SCAN_INTERVAL: Final = timedelta(seconds=15)

CONF_SCAN_INTERVAL: Final = "scan_interval"
CONF_DEFAULT_POSITION: Final = "default_position"
DEFAULT_POSITION: Final = "top_right"
CONF_DEFAULT_DURATION: Final = "default_duration"
CONF_DEFAULT_MUTED: Final = "default_muted"
CONF_DEFAULT_MEDIA_WIDTH: Final = "default_media_width"
CONF_DEFAULT_MEDIA_HEIGHT: Final = "default_media_height"
CONF_DEFAULT_TITLE_COLOR: Final = "default_title_color"
CONF_DEFAULT_TITLE_SIZE: Final = "default_title_size"
CONF_DEFAULT_MESSAGE_COLOR: Final = "default_message_color"
CONF_DEFAULT_MESSAGE_SIZE: Final = "default_message_size"
CONF_DEFAULT_BACKGROUND_COLOR: Final = "default_background_color"
CONF_DEFAULT_BORDER_COLOR: Final = "default_border_color"
CONF_DEFAULT_BORDER_WIDTH: Final = "default_border_width"
CONF_DEFAULT_CORNER_RADIUS: Final = "default_corner_radius"
CONF_NAME_SUFFIX: Final = "name_suffix"
# internal marker: which suffix we last applied to the entity registry names
CONF_NAME_SUFFIX_APPLIED: Final = "name_suffix_applied"

SERVICE_SHOW: Final = "show"
SERVICE_FIX_PERMISSION: Final = "fix_permission"
SERVICE_DISMISS: Final = "dismiss"

ATTR_TITLE: Final = "title"
ATTR_MESSAGE: Final = "message"
ATTR_DURATION: Final = "duration"
ATTR_POPUP_ID: Final = "popup_id"
ATTR_POSITION: Final = "position"
ATTR_TITLE_COLOR: Final = "title_color"
ATTR_TITLE_SIZE: Final = "title_size"
ATTR_MESSAGE_COLOR: Final = "message_color"
ATTR_MESSAGE_SIZE: Final = "message_size"
ATTR_BACKGROUND_COLOR: Final = "background_color"
ATTR_IMAGE_URL: Final = "image_url"
ATTR_VIDEO_URL: Final = "video_url"
ATTR_WEB_URL: Final = "web_url"
ATTR_MEDIA_WIDTH: Final = "media_width"
ATTR_MEDIA_HEIGHT: Final = "media_height"
ATTR_MUTED: Final = "muted"
ATTR_CAMERA_ENTITY: Final = "camera_entity"
ATTR_CAMERA_MODE: Final = "camera_mode"
ATTR_TTS: Final = "tts"
ATTR_TTS_LANGUAGE: Final = "tts_language"
ATTR_BUTTONS: Final = "buttons"
ATTR_SHOW_PROGRESS: Final = "show_progress"
ATTR_URGENCY: Final = "urgency"
# app >= 0.7.0: explicit border styling, each overriding its part of `urgency`
ATTR_BORDER_COLOR: Final = "border_color"
ATTR_BORDER_WIDTH: Final = "border_width"
ATTR_CORNER_RADIUS: Final = "corner_radius"

URGENCIES: Final = ["info", "warning", "critical"]

# webhook that receives popup-button presses from the app; fires EVENT_BUTTON
WEBHOOK_ID: Final = "pipup_buttons"
EVENT_BUTTON: Final = "pipup_button"
# hass.data key holding the single-use button-callback tokens
DATA_BUTTON_TOKENS: Final = "button_tokens"
# how long a button-callback token stays valid after the popup is shown
BUTTON_TOKEN_TTL: Final = timedelta(minutes=15)

# screen on/off (app >= 0.7.0): /state publishes what the device can actually do
POWER_STATE_ON: Final = "on"
POWER_STATE_OFF: Final = "off"
# how long the screen switch trusts its own optimistic state: the app's screenOn
# comes from PowerManager.isInteractive and lags a poll behind a fresh wake
POWER_OPTIMISTIC_TTL: Final = timedelta(seconds=20)
# extra refresh after a power call, to pick up the real state once it settled
POWER_SETTLE_DELAY: Final = 5

# repair issue raised when the overlay app-op is missing (popups stay invisible)
ISSUE_NO_OVERLAY: Final = "no_overlay_permission"

ATTR_PERMISSION: Final = "permission"
# "app" opens PiPup's own permission screen, "next" the first missing permission
PERMISSIONS: Final = ["app", "next", "overlay", "install", "admin", "accessibility"]

CAMERA_MODE_STREAM: Final = "stream"
CAMERA_MODE_MJPEG: Final = "mjpeg"
CAMERA_MODE_SNAPSHOT: Final = "snapshot"

POSITIONS: Final = {
    "top_right": 0,
    "top_left": 1,
    "bottom_right": 2,
    "bottom_left": 3,
    "center": 4,
}
