"""Constants for the PiPup integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from datetime import timedelta
from typing import Final

DOMAIN: Final = "pipup"

DEFAULT_PORT: Final = 7979
DEFAULT_SCAN_INTERVAL: Final = timedelta(seconds=15)

CONF_SCAN_INTERVAL: Final = "scan_interval"
CONF_DEFAULT_POSITION: Final = "default_position"
DEFAULT_POSITION: Final = "top_right"
CONF_DEFAULT_DURATION: Final = "default_duration"
CONF_DEFAULT_MUTED: Final = "default_muted"
CONF_DEFAULT_MEDIA_WIDTH: Final = "default_media_width"
CONF_DEFAULT_MEDIA_HEIGHT: Final = "default_media_height"
CONF_DEFAULT_TITLE_COLOR: Final = "default_title_color"
CONF_DEFAULT_TITLE_SIZE: Final = "default_title_size"
CONF_DEFAULT_MESSAGE_COLOR: Final = "default_message_color"
CONF_DEFAULT_MESSAGE_SIZE: Final = "default_message_size"
CONF_DEFAULT_BACKGROUND_COLOR: Final = "default_background_color"
CONF_NAME_SUFFIX: Final = "name_suffix"
# internal marker: which suffix we last applied to the entity registry names
CONF_NAME_SUFFIX_APPLIED: Final = "name_suffix_applied"

SERVICE_SHOW: Final = "show"
SERVICE_DISMISS: Final = "dismiss"

ATTR_TITLE: Final = "title"
ATTR_MESSAGE: Final = "message"
ATTR_DURATION: Final = "duration"
ATTR_POPUP_ID: Final = "popup_id"
ATTR_POSITION: Final = "position"
ATTR_TITLE_COLOR: Final = "title_color"
ATTR_TITLE_SIZE: Final = "title_size"
ATTR_MESSAGE_COLOR: Final = "message_color"
ATTR_MESSAGE_SIZE: Final = "message_size"
ATTR_BACKGROUND_COLOR: Final = "background_color"
ATTR_IMAGE_URL: Final = "image_url"
ATTR_VIDEO_URL: Final = "video_url"
ATTR_WEB_URL: Final = "web_url"
ATTR_MEDIA_WIDTH: Final = "media_width"
ATTR_MEDIA_HEIGHT: Final = "media_height"
ATTR_MUTED: Final = "muted"
ATTR_CAMERA_ENTITY: Final = "camera_entity"
ATTR_CAMERA_MODE: Final = "camera_mode"
ATTR_TTS: Final = "tts"
ATTR_TTS_LANGUAGE: Final = "tts_language"

CAMERA_MODE_STREAM: Final = "stream"
CAMERA_MODE_MJPEG: Final = "mjpeg"
CAMERA_MODE_SNAPSHOT: Final = "snapshot"

POSITIONS: Final = {
    "top_right": 0,
    "top_left": 1,
    "bottom_right": 2,
    "bottom_left": 3,
    "center": 4,
}
