"""Constants for the PiPup integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from datetime import timedelta
from typing import Final

DOMAIN: Final = "pipup"

DEFAULT_PORT: Final = 7979
DEFAULT_SCAN_INTERVAL: Final = timedelta(seconds=15)
# While an app self-update runs: poll fast enough that the download percentage moves
# (an 8 MB APK takes a few seconds to ~15 s on Wi-Fi), back to normal afterwards.
UPDATE_POLL_INTERVAL: Final = timedelta(seconds=2)
# with push active the poll is only a liveness heartbeat (app >= 0.24.0)
PUSH_HEARTBEAT_INTERVAL: Final = timedelta(seconds=60)

CONF_SCAN_INTERVAL: Final = "scan_interval"
# Where app releases come from: "github:<owner>/<repo>", an http(s)
# folder URL holding releases.json + the APKs (a LAN mirror), or "off". Sent to the
# app too (app >= 0.24.0), so the TV's own check and this entity agree.
CONF_UPDATE_SOURCE: Final = "update_source"
DEFAULT_UPDATE_SOURCE: Final = "github:mhoogenbosch/PiPup"
UPDATE_SOURCE_OFF: Final = "off"
CONF_DEFAULT_POSITION: Final = "default_position"
DEFAULT_POSITION: Final = "top_right"
CONF_DEFAULT_DURATION: Final = "default_duration"
CONF_DEFAULT_MUTED: Final = "default_muted"
CONF_DEFAULT_MEDIA_WIDTH: Final = "default_media_width"
CONF_DEFAULT_MEDIA_HEIGHT: Final = "default_media_height"
CONF_DEFAULT_TITLE_COLOR: Final = "default_title_color"
CONF_DEFAULT_TITLE_SIZE: Final = "default_title_size"
CONF_DEFAULT_MESSAGE_COLOR: Final = "default_message_color"
CONF_DEFAULT_MESSAGE_SIZE: Final = "default_message_size"
CONF_DEFAULT_BACKGROUND_COLOR: Final = "default_background_color"
CONF_DEFAULT_BORDER_COLOR: Final = "default_border_color"
CONF_DEFAULT_BORDER_WIDTH: Final = "default_border_width"
CONF_DEFAULT_CORNER_RADIUS: Final = "default_corner_radius"
CONF_DEFAULT_ICON_POSITION: Final = "default_icon_position"
CONF_DEFAULT_ICON_WIDTH: Final = "default_icon_width"
CONF_DEFAULT_SOUND: Final = "default_sound"
CONF_DEFAULT_DISMISS_SCREENSAVER: Final = "default_dismiss_screensaver"
CONF_DEFAULT_BUTTON_SIZE: Final = "default_button_size"
CONF_DEFAULT_ANIMATION: Final = "default_animation"
CONF_NAME_SUFFIX: Final = "name_suffix"
# internal marker: which suffix we last applied to the entity registry names
CONF_NAME_SUFFIX_APPLIED: Final = "name_suffix_applied"

SERVICE_SHOW: Final = "show"
SERVICE_FIX_PERMISSION: Final = "fix_permission"
SERVICE_DISMISS: Final = "dismiss"
SERVICE_SYNC: Final = "sync"

ATTR_TITLE: Final = "title"
ATTR_MESSAGE: Final = "message"
ATTR_DURATION: Final = "duration"
ATTR_POPUP_ID: Final = "popup_id"
ATTR_POSITION: Final = "position"
ATTR_TITLE_COLOR: Final = "title_color"
ATTR_TITLE_SIZE: Final = "title_size"
ATTR_MESSAGE_COLOR: Final = "message_color"
ATTR_MESSAGE_SIZE: Final = "message_size"
ATTR_BACKGROUND_COLOR: Final = "background_color"
ATTR_IMAGE_URL: Final = "image_url"
ATTR_VIDEO_URL: Final = "video_url"
ATTR_WEB_URL: Final = "web_url"
ATTR_MEDIA_WIDTH: Final = "media_width"
ATTR_MEDIA_HEIGHT: Final = "media_height"
ATTR_MUTED: Final = "muted"
ATTR_CAMERA_ENTITY: Final = "camera_entity"
ATTR_CAMERA_MODE: Final = "camera_mode"
ATTR_TTS: Final = "tts"
ATTR_TTS_LANGUAGE: Final = "tts_language"
ATTR_BUTTONS: Final = "buttons"
ATTR_SHOW_PROGRESS: Final = "show_progress"
ATTR_URGENCY: Final = "urgency"
# app >= 0.7.0: explicit border styling, each overriding its part of `urgency`
ATTR_BORDER_COLOR: Final = "border_color"
ATTR_BORDER_WIDTH: Final = "border_width"
ATTR_CORNER_RADIUS: Final = "corner_radius"
# app >= 0.17.0: still image shown over a video/web stream until its first frame renders
ATTR_POSTER_URL: Final = "poster_url"
# app >= 0.13.0: an icon beside the title/message block
ATTR_ICON: Final = "icon"
ATTR_ICON_POSITION: Final = "icon_position"
ATTR_ICON_WIDTH: Final = "icon_width"
# app >= 0.18.0: notification sound ("default" = built-in chime, or a URL) and screensaver handling
ATTR_SOUND: Final = "sound"
ATTR_SOUND_VOLUME: Final = "sound_volume"
ATTR_DISMISS_SCREENSAVER: Final = "dismiss_screensaver"
# app >= 0.19.0: compact buttons and entrance/exit animations
# app >= 0.19.1: outer margin of the popup around its content
ATTR_PADDING: Final = "padding"
#, app >= 0.24.0: see-through popups
ATTR_OPACITY: Final = "opacity"
ATTR_TRANSPARENT: Final = "transparent"
#, app >= 0.24.0: several popups at once
ATTR_BRING_TO_FRONT: Final = "bring_to_front"
ATTR_ALL: Final = "all"
ATTR_BUTTON_SIZE: Final = "button_size"
ATTR_ANIMATION: Final = "animation"

URGENCIES: Final = ["info", "warning", "critical"]
ICON_POSITIONS: Final = ["left", "right"]
ANIMATIONS: Final = ["none", "fade", "slide_left", "slide_right", "slide_top", "slide_bottom"]
DEFAULT_ICON_POSITION: Final = "left"

# Push (app >= 0.24.0): per-entry webhook id, stored in entry data.
# The id is the secret: the TV POSTs its /state JSON there on every change.
CONF_PUSH_WEBHOOK_ID: Final = "push_webhook_id"
# fired for every pushed event: event, reason, popup_id, removed_id, replaced_id, device_id
EVENT_PUSH: Final = "pipup_event"

# webhook that receives popup-button presses from the app; fires EVENT_BUTTON
WEBHOOK_ID: Final = "pipup_buttons"
EVENT_BUTTON: Final = "pipup_button"
# hass.data key holding the single-use button-callback tokens
DATA_BUTTON_TOKENS: Final = "button_tokens"
# how long a button-callback token stays valid after the popup is shown
BUTTON_TOKEN_TTL: Final = timedelta(minutes=15)

# screen on/off (app >= 0.7.0): /state publishes what the device can actually do
POWER_STATE_ON: Final = "on"
POWER_STATE_OFF: Final = "off"
# how long the screen switch trusts its own optimistic state: the app's screenOn
# comes from PowerManager.isInteractive and lags a poll behind a fresh wake
POWER_OPTIMISTIC_TTL: Final = timedelta(seconds=20)
# extra refresh after a power call, to pick up the real state once it settled
POWER_SETTLE_DELAY: Final = 5

# repair issue raised when the overlay app-op is missing (popups stay invisible)
ISSUE_NO_OVERLAY: Final = "no_overlay_permission"
# Same problem, different text: an issue may carry either a description (nothing to
# press) or a fix flow, never both - and whether the TV can show the screen decides
# which of the two the user gets.
ISSUE_NO_OVERLAY_FIXABLE: Final = "no_overlay_permission_fixable"

ATTR_PERMISSION: Final = "permission"
# "app" opens PiPup's own permission screen, "next" the first missing permission
PERMISSIONS: Final = ["app", "next", "overlay", "install", "admin", "accessibility"]

CAMERA_MODE_STREAM: Final = "stream"
CAMERA_MODE_MJPEG: Final = "mjpeg"
CAMERA_MODE_SNAPSHOT: Final = "snapshot"

POSITIONS: Final = {
    "top_right": 0,
    "top_left": 1,
    "bottom_right": 2,
    "bottom_left": 3,
    "center": 4,
    "top_center": 5,
    "bottom_center": 6,
}

# Positions the app only understands from a given version on. Older apps reject an
# unknown ordinal (the JSON parser fails the whole /notify), so pipup.show refuses to
# send them there instead of failing silently on the TV.
POSITION_MIN_APP_VERSION: Final = {"top_center": "0.22.0", "bottom_center": "0.22.0"}
# Overlays (1.20.0): named web popups pinned over the TV picture, one
# config subentry each, with their settings as entities. Pages are a per-TV list in
# the options, one "Name | URL" line each.
SUBENTRY_OVERLAY: Final = "overlay"
CONF_OVERLAY_POPUP_ID: Final = "popup_id"
CONF_OVERLAY_PAGES: Final = "overlay_pages"
OVERLAY_CUSTOM_PAGE: Final = "Custom URL"
OVERLAY_LAYOUT_CUSTOM: Final = "Custom"
# name: (width, height, position)
OVERLAY_LAYOUTS: Final = {
    "Column right": (420, 900, "top_right"),
    "Column left": (420, 900, "top_left"),
    "Corner small": (480, 300, "top_right"),
    "Corner large": (720, 480, "top_right"),
    "Strip bottom": (1880, 240, "bottom_left"),
}
OVERLAY_SOUNDS: Final = ["none", "chime"]
OVERLAY_DEFAULTS: Final = {
    "page": None,  # first page in the list
    "custom_url": "",
    "layout": "Column right",
    "position": "top_right",
    "width": 420,
    "height": 900,
    "duration": 0,
    "padding": 6,
    "corner_radius": 0,
    "border_width": 0,
    "page_opacity": 100,
    "background_opacity": 80,
    "background_color": "#000000",
    "border_color": "",
    "title": "",
    "animation": "none",
    "sound": "none",
    "muted": True,
    "transparent": False,
    "bring_to_front": False,
}
# a settings change while the overlay is up redraws it after this many seconds, so a
# dragged slider sends one popup, not one per step
OVERLAY_REDRAW_DELAY: Final = 1.0
# how long the Show switch trusts its own call before the TV's push confirms it
OVERLAY_OPTIMISTIC_SECONDS: Final = 6
SIGNAL_OVERLAY_UPDATED: Final = "pipup_overlay_updated_{}"
