"""Data coordinator for the PiPup integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
from datetime import timedelta
from typing import Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import CONF_HOST, CONF_PORT
from homeassistant.core import HomeAssistant
from homeassistant.helpers import issue_registry as ir
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.update_coordinator import (
    DataUpdateCoordinator,
    UpdateFailed,
)

from .api import PiPupClient, PiPupError
from .const import (
    CONF_SCAN_INTERVAL,
    DEFAULT_SCAN_INTERVAL,
    DOMAIN,
    ISSUE_NO_OVERLAY,
)

_LOGGER = logging.getLogger(__name__)


class PiPupCoordinator(DataUpdateCoordinator[dict[str, Any]]):
    """Polls /state of a single PiPup device.

    FireTV sticks cut their network entirely in standby, so after the first
    successful refresh a failed poll only flips ``online`` to False and keeps
    the last data — entities stay available instead of flapping to
    unavailable; the connectivity sensor reflects reachability.
    """

    config_entry: ConfigEntry

    def __init__(self, hass: HomeAssistant, entry: ConfigEntry) -> None:
        """Initialize coordinator."""
        self.client = PiPupClient(
            async_get_clientsession(hass),
            entry.data[CONF_HOST],
            entry.data[CONF_PORT],
        )
        self.online = False
        # tri-state: None = not yet known, so the first poll always evaluates
        self._overlay_ok: bool | None = None

        scan_interval = entry.options.get(CONF_SCAN_INTERVAL)
        update_interval = (
            timedelta(seconds=scan_interval)
            if scan_interval
            else DEFAULT_SCAN_INTERVAL
        )

        super().__init__(
            hass,
            _LOGGER,
            name=f"{DOMAIN}_{entry.data[CONF_HOST]}",
            update_interval=update_interval,
            config_entry=entry,
        )

    async def _async_update_data(self) -> dict[str, Any]:
        """Fetch /state from the device."""
        try:
            data = await self.client.state()
        except PiPupError as err:
            self.online = False
            if self.data is None:
                # first refresh: fail so setup retries until the TV answers
                # (conditional entities and the id migration need real data)
                raise UpdateFailed(str(err)) from err
            _LOGGER.debug("PiPup at %s unreachable: %s", self.client.host, err)
            return self.data
        self.online = True
        self._check_overlay_permission(data)
        return data

    def _check_overlay_permission(self, data: dict[str, Any]) -> None:
        """Raise/clear a repair issue for a missing overlay app-op (app >= 0.7.0).

        Without SYSTEM_ALERT_WINDOW the TV answers every popup with HTTP 200 and
        shows nothing, so nothing else in HA would ever reveal this. The app-op also
        resets on every reinstall, hence a repair rather than a one-off log line.
        Only touched on a change: the registry is not a polling target.
        """
        permissions = data.get("permissions")
        if not isinstance(permissions, dict):
            return  # older app: it cannot tell us
        overlay = permissions.get("overlay")
        if overlay is None or overlay == self._overlay_ok:
            return

        self._overlay_ok = bool(overlay)
        issue_id = f"{ISSUE_NO_OVERLAY}_{self.config_entry.entry_id}"
        if overlay:
            ir.async_delete_issue(self.hass, DOMAIN, issue_id)
            return
        ir.async_create_issue(
            self.hass,
            DOMAIN,
            issue_id,
            is_fixable=False,
            severity=ir.IssueSeverity.WARNING,
            translation_key=ISSUE_NO_OVERLAY,
            translation_placeholders={
                "name": self.config_entry.title,
                "host": self.client.host,
            },
            learn_more_url="https://github.com/mhoogenbosch/PiPup#install",
        )

    async def async_refresh_soon(self) -> None:
        """Refresh state right after a show/dismiss call."""
        await self.async_request_refresh()
