"""Data coordinator for the PiPup integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
from datetime import timedelta
from typing import Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import CONF_HOST, CONF_PORT
from homeassistant.core import HomeAssistant
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.update_coordinator import (
    DataUpdateCoordinator,
    UpdateFailed,
)

from .api import PiPupClient, PiPupError
from .const import CONF_SCAN_INTERVAL, DEFAULT_SCAN_INTERVAL, DOMAIN

_LOGGER = logging.getLogger(__name__)


class PiPupCoordinator(DataUpdateCoordinator[dict[str, Any]]):
    """Polls /state of a single PiPup device."""

    config_entry: ConfigEntry

    def __init__(self, hass: HomeAssistant, entry: ConfigEntry) -> None:
        """Initialize coordinator."""
        self.client = PiPupClient(
            async_get_clientsession(hass),
            entry.data[CONF_HOST],
            entry.data[CONF_PORT],
        )

        scan_interval = entry.options.get(CONF_SCAN_INTERVAL)
        update_interval = (
            timedelta(seconds=scan_interval)
            if scan_interval
            else DEFAULT_SCAN_INTERVAL
        )

        super().__init__(
            hass,
            _LOGGER,
            name=f"{DOMAIN}_{entry.data[CONF_HOST]}",
            update_interval=update_interval,
            config_entry=entry,
        )

    async def _async_update_data(self) -> dict[str, Any]:
        """Fetch /state from the device."""
        try:
            return await self.client.state()
        except PiPupError as err:
            raise UpdateFailed(str(err)) from err

    async def async_refresh_soon(self) -> None:
        """Refresh state right after a show/dismiss call."""
        await self.async_request_refresh()
