"""Data coordinator for the PiPup integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import asyncio
import logging
import secrets
from datetime import timedelta
from typing import Any

from homeassistant.components import webhook as webhook_component
from homeassistant.config_entries import ConfigEntry
from homeassistant.const import CONF_HOST, CONF_PORT
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers import issue_registry as ir, device_registry as dr
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.network import NoURLAvailableError, get_url
from homeassistant.helpers.update_coordinator import (
    DataUpdateCoordinator,
    UpdateFailed,
)

from .api import PiPupClient, PiPupError
from .const import (
    CONF_PUSH_WEBHOOK_ID,
    CONF_SCAN_INTERVAL,
    CONF_UPDATE_SOURCE,
    DEFAULT_UPDATE_SOURCE,
    UPDATE_SOURCE_OFF,
    DEFAULT_SCAN_INTERVAL,
    DOMAIN,
    EVENT_PUSH,
    ISSUE_NO_OVERLAY,
    ISSUE_NO_OVERLAY_FIXABLE,
    PUSH_HEARTBEAT_INTERVAL,
    UPDATE_POLL_INTERVAL,
)

_LOGGER = logging.getLogger(__name__)

# The app answers /notify and /cancel before the popup view is actually created or
# torn down: measured on a Nokia 8010, /state read ~20 ms after the reply still had no
# popup, ~75 ms later it did. Refreshing inside that window shows the old state until
# the next poll, so the post-call refresh waits this long first.
POST_CALL_SETTLE_SECONDS = 0.5


def popups_on_screen(data: dict[str, Any] | None) -> list[dict[str, Any]]:
    """Every popup on the TV, in stack order (last = on top).

    App >= 0.24.0 reports the list itself; an older app shows one
    popup at a time, reported as `popup` while `visible`.
    """
    data = data or {}
    if isinstance(data.get("popups"), list):
        return [p for p in data["popups"] if isinstance(p, dict)]
    if data.get("visible") and isinstance(data.get("popup"), dict):
        return [data["popup"]]
    return []


def popup_ids(data: dict[str, Any] | None) -> list[str | None]:
    """Ids of the popups on the TV, in stack order; None for a popup without an id."""
    return [p.get("id") for p in popups_on_screen(data)]


class PiPupCoordinator(DataUpdateCoordinator[dict[str, Any]]):
    """Polls /state of a single PiPup device.

    FireTV sticks cut their network entirely in standby, so after the first
    successful refresh a failed poll only flips ``online`` to False and keeps
    the last data — entities stay available instead of flapping to
    unavailable; the connectivity sensor reflects reachability.
    """

    config_entry: ConfigEntry

    def __init__(self, hass: HomeAssistant, entry: ConfigEntry) -> None:
        """Initialize coordinator."""
        self.client = PiPupClient(
            async_get_clientsession(hass),
            entry.data[CONF_HOST],
            entry.data[CONF_PORT],
        )
        self.online = False
        # set once the push webhook is registered (app >= 0.24.0); polling stops then
        self._webhook_id: str | None = None
        self._asserting = False
        self._setting_up_push = False
        # update source the entities were built with; a change reloads the entry
        self.applied_update_source: str | None = None
        # event/reason/removedId/replacedId of the last push, read by the overlays
        # to say why their popup left the screen
        self.last_event: dict[str, Any] = {}
        # the entry's OverlayManager, set in async_setup_entry
        self.overlays: Any = None
        self.applied_pages: str | None = None

        scan_interval = entry.options.get(CONF_SCAN_INTERVAL)
        update_interval = (
            timedelta(seconds=scan_interval)
            if scan_interval
            else DEFAULT_SCAN_INTERVAL
        )

        super().__init__(
            hass,
            _LOGGER,
            name=f"{DOMAIN}_{entry.data[CONF_HOST]}",
            update_interval=update_interval,
            config_entry=entry,
        )
        self._normal_interval = update_interval
        self._sw_version: str | None = None

    def set_update_polling(self, active: bool) -> None:
        """Poll every UPDATE_POLL_INTERVAL while an app update runs, normally otherwise.

        Called by the update entity on every state change; a no-op when the interval
        already matches. The new interval applies from the next scheduled refresh.
        """
        target = UPDATE_POLL_INTERVAL if active else self._normal_interval
        if self.update_interval != target:
            self.update_interval = target

    async def _async_update_data(self) -> dict[str, Any]:
        """Fetch /state from the device."""
        try:
            data = await self.client.state()
        except PiPupError as err:
            self.online = False
            if self.data is None:
                # first refresh: fail so setup retries until the TV answers
                # (conditional entities and the id migration need real data)
                raise UpdateFailed(str(err)) from err
            _LOGGER.debug("PiPup at %s unreachable: %s", self.client.host, err)
            return self.data
        self.online = True
        self._check_overlay_permission(data)
        self._sync_sw_version(data)
        push = data.get("push") or {}
        # The app lost its webhook (reinstall wipes its prefs): set it again.
        if self._webhook_id and not push.get("webhook"):
            self.hass.async_create_task(self.async_assert_webhook())
        # The app gained push after setup (self-update from an app < 0.24.0): set it
        # up now instead of polling until the next reload. HA starts the task eagerly,
        # before this data is stored, so the support is passed in explicitly.
        elif self._webhook_id is None and push.get("supported") and not self._setting_up_push:
            self._setting_up_push = True
            self.hass.async_create_task(self._async_setup_push_later())
        return data

    async def _async_setup_push_later(self) -> None:
        """Set up push for an app that gained it after setup."""
        try:
            await self.async_setup_push(supported=True)
        finally:
            self._setting_up_push = False

    def _sync_sw_version(self, data: dict[str, Any]) -> None:
        """Keep the device's sw_version equal to the app version on the TV.

        DeviceInfo only sets it when the entities are created, so after a
        self-update the device page showed the old version until the next reload.
        Only touches the registry when the version actually changed.
        """
        version = data.get("version")
        if not version or version == self._sw_version:
            return
        from . import _async_get_own_device  # local: __init__ imports this module

        registry = dr.async_get(self.hass)
        entry = self.config_entry
        device = _async_get_own_device(
            registry, (DOMAIN, entry.unique_id or entry.entry_id), entry.entry_id
        )
        if device is None:
            return  # entities not set up yet; DeviceInfo carries the version then
        if device.sw_version != version:
            registry.async_update_device(device.id, sw_version=version)
        self._sw_version = version

    @property
    def push_supported(self) -> bool:
        """True when the app can push its state (app >= 0.24.0)."""
        return bool(((self.data or {}).get("push") or {}).get("supported"))

    @property
    def push_active(self) -> bool:
        """True when this entry receives pushes and does not poll."""
        return self._webhook_id is not None

    async def async_setup_push(self, supported: bool | None = None) -> None:
        """Register this entry's push webhook and hand its URL to the app.

        From then on the coordinator does not poll: the app POSTs its /state JSON on
        every change, and /state is read only at setup, after this integration's own
        calls, and on Sync. An app without push keeps the timed poll.
        """
        if self._webhook_id is not None or not (supported or self.push_supported):
            return
        entry = self.config_entry
        webhook_id = entry.data.get(CONF_PUSH_WEBHOOK_ID)
        if not webhook_id:
            webhook_id = secrets.token_hex(16)
            self.hass.config_entries.async_update_entry(
                entry, data={**entry.data, CONF_PUSH_WEBHOOK_ID: webhook_id}
            )
        try:
            webhook_component.async_register(
                self.hass,
                DOMAIN,
                f"PiPup push ({entry.title})",
                webhook_id,
                self._async_handle_push,
                local_only=True,
                allowed_methods=["POST"],
            )
        except ValueError:
            _LOGGER.debug("Push webhook for %s already registered", entry.title)
        self._webhook_id = webhook_id
        # Pushes make every change immediate; a slow heartbeat poll stays so a TV that
        # sleeps or drops off the network still turns unavailable (a push never says so).
        self._normal_interval = max(self._normal_interval, PUSH_HEARTBEAT_INTERVAL)
        if self.update_interval != UPDATE_POLL_INTERVAL:
            self.update_interval = self._normal_interval
        await self.async_assert_webhook()

    @callback
    def async_teardown_push(self) -> None:
        """Unregister the push webhook (entry unload)."""
        if self._webhook_id is not None:
            webhook_component.async_unregister(self.hass, self._webhook_id)
            self._webhook_id = None

    async def async_assert_webhook(self) -> None:
        """Send the webhook URL to the app (it answers with a "settings" push)."""
        if self._webhook_id is None or self._asserting:
            return
        self._asserting = True
        try:
            base = get_url(self.hass, allow_external=False, prefer_external=False)
            await self.client.settings(webhook=f"{base}/api/webhook/{self._webhook_id}")
        except NoURLAvailableError:
            _LOGGER.warning(
                "PiPup push for %s: HA has no internal URL the TV can reach; "
                "set one under Settings > System > Network", self.config_entry.title
            )
        except PiPupError as err:
            _LOGGER.warning("PiPup push for %s: cannot set webhook: %s",
                            self.config_entry.title, err)
        finally:
            self._asserting = False

    async def async_apply_app_settings(self) -> None:
        """Send the update source option to the app (app >= 0.24.0), so the TV's own
        release check uses the same source as the update entity, or none at all."""
        if not self.push_supported:
            return  # older app: no updateSource setting
        source = self.config_entry.options.get(CONF_UPDATE_SOURCE) or DEFAULT_UPDATE_SOURCE
        values = (
            {"updateChecks": "false"}
            if source == UPDATE_SOURCE_OFF
            else {"updateChecks": "true", "updateSource": source}
        )
        try:
            await self.client.settings(**values)
        except PiPupError as err:
            _LOGGER.warning("PiPup %s: cannot set update source: %s",
                            self.config_entry.title, err)

    async def async_sync(self) -> None:
        """Read /state now and re-assert the webhook (Sync button, pipup.sync)."""
        await self.async_refresh()
        if self._webhook_id is None:
            await self.async_setup_push()
        else:
            await self.async_assert_webhook()
        await self.async_apply_app_settings()

    async def _async_handle_push(self, hass: HomeAssistant, webhook_id: str, request) -> None:
        """Take one pushed state from the app."""
        try:
            data = await request.json()
        except ValueError:
            _LOGGER.warning("PiPup push: invalid JSON on %s", self.config_entry.title)
            return
        if not isinstance(data, dict) or data.get("app") != "PiPup":
            return
        extra = {
            k: data.pop(k, None)
            for k in ("event", "reason", "shownId", "removedId", "replacedId")
        }
        self.online = True
        self._check_overlay_permission(data)
        self._sync_sw_version(data)
        self.last_event = extra
        self.async_set_updated_data(data)
        from . import _async_get_own_device  # local: __init__ imports this module

        entry = self.config_entry
        device = _async_get_own_device(
            dr.async_get(hass), (DOMAIN, entry.unique_id or entry.entry_id), entry.entry_id
        )
        hass.bus.async_fire(
            EVENT_PUSH,
            {
                "event": extra["event"],
                "reason": extra["reason"],
                "popup_id": (data.get("popup") or {}).get("id"),
                "shown_id": extra["shownId"],
                "popup_ids": popup_ids(data),
                "removed_id": extra["removedId"],
                "replaced_id": extra["replacedId"],
                "device_id": device.id if device else None,
                "pipup_id": data.get("id"),
                "device_name": data.get("name"),
            },
        )

    def _check_overlay_permission(self, data: dict[str, Any]) -> None:
        """Raise/clear a repair issue for a missing overlay app-op (app >= 0.7.0).

        Without SYSTEM_ALERT_WINDOW the TV answers every popup with HTTP 200 and
        shows nothing, so nothing else in HA would ever reveal this. The app-op also
        resets on every reinstall, hence a repair rather than a one-off log line.
        Only touched on a change: the registry is not a polling target.
        """
        permissions = data.get("permissions")
        if not isinstance(permissions, dict):
            return  # older app: it cannot tell us
        overlay = permissions.get("overlay")
        if overlay is None:
            return

        issue_id = f"{ISSUE_NO_OVERLAY}_{self.config_entry.entry_id}"
        # Ask the registry rather than remembering the last value: the repair flow
        # closes the issue while the permission is still missing (someone has to
        # confirm it on the TV), and this is what raises it again if they did not.
        exists = ir.async_get(self.hass).async_get_issue(DOMAIN, issue_id) is not None

        if overlay:
            if exists:
                ir.async_delete_issue(self.hass, DOMAIN, issue_id)
            return
        if exists:
            return
        # fixable when the app can open the screen itself (app >= 0.8.0); otherwise only
        # adb can do it, and then the issue carries the command as its description
        fixable = bool((permissions.get("fixable") or {}).get("overlay"))
        ir.async_create_issue(
            self.hass,
            DOMAIN,
            issue_id,
            is_fixable=fixable,
            severity=ir.IssueSeverity.WARNING,
            translation_key=ISSUE_NO_OVERLAY_FIXABLE if fixable else ISSUE_NO_OVERLAY,
            translation_placeholders={
                "name": self.config_entry.title,
                "host": self.client.host,
            },
            data={"entry_id": self.config_entry.entry_id},
            learn_more_url="https://github.com/mhoogenbosch/PiPup#install",
        )

    async def async_refresh_soon(self) -> None:
        """Refresh state right after a show/dismiss call.

        Deliberately ``async_refresh`` and not ``async_request_refresh``: the latter is
        debounced (10 s cooldown), so whenever the regular poll ran recently the
        "immediate" refresh was postponed and the popup sensor showed the previous
        popup — or none — for up to a full poll interval. An automation reacting to a
        popup within seconds of showing it needs the real state now; one extra
        /state round-trip per show/dismiss is cheap. The short settle delay is for
        the app, which replies before the popup exists (see POST_CALL_SETTLE_SECONDS).
        """
        await asyncio.sleep(POST_CALL_SETTLE_SECONDS)
        await self.async_refresh()
