"""Diagnostics for the PiPup integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from typing import Any

from homeassistant.core import HomeAssistant

from .coordinator import PiPupCoordinator


async def async_get_config_entry_diagnostics(
    hass: HomeAssistant, entry
) -> dict[str, Any]:
    """Return diagnostics for a config entry."""
    coordinator: PiPupCoordinator = entry.runtime_data
    return {
        "entry": {
            "title": entry.title,
            "data": dict(entry.data),
            "options": dict(entry.options),
        },
        "state": coordinator.data,
        "last_update_success": coordinator.last_update_success,
    }
