"""Diagnostics for the PiPup integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from typing import Any

from homeassistant.components.diagnostics import async_redact_data
from homeassistant.core import HomeAssistant

from .const import CONF_PUSH_WEBHOOK_ID
from .coordinator import PiPupCoordinator

# The push webhook id is the only secret the app needs to post state into HA.
TO_REDACT = {CONF_PUSH_WEBHOOK_ID}


async def async_get_config_entry_diagnostics(
    hass: HomeAssistant, entry
) -> dict[str, Any]:
    """Return diagnostics for a config entry."""
    coordinator: PiPupCoordinator = entry.runtime_data
    return {
        "entry": {
            "title": entry.title,
            "data": async_redact_data(dict(entry.data), TO_REDACT),
            "options": async_redact_data(dict(entry.options), TO_REDACT),
        },
        "state": coordinator.data,
        "last_update_success": coordinator.last_update_success,
        # Fetched live (app >= 0.9.0): per permission which activity resolves its
        # settings screen, whether that is a vendor placeholder, whether a background
        # activity launch is allowed at all, and how the last fix attempt ended. This is
        # the file to attach to a "the fix button does nothing" report.
        "permission_diagnose": await coordinator.client.diagnose(),
    }
