"""Shared base entity for the PiPup integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from homeassistant.helpers.device_registry import DeviceInfo
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .const import DOMAIN
from .coordinator import PiPupCoordinator


class PiPupEntity(CoordinatorEntity[PiPupCoordinator]):
    """Base entity: shared device info and unique id scheme."""

    _attr_has_entity_name = True

    def __init__(self, coordinator: PiPupCoordinator, entry, key: str) -> None:
        """Initialize the entity."""
        super().__init__(coordinator)
        device = coordinator.data.get("device") or {}
        self._attr_unique_id = f"{entry.unique_id or entry.entry_id}_{key}"
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, entry.unique_id or entry.entry_id)},
            name=entry.title,
            manufacturer=device.get("manufacturer") or "PiPup (fork)",
            model=device.get("model") or "Android TV popup service",
            sw_version=coordinator.data.get("version"),
            configuration_url=(
                f"http://{coordinator.client.host}:{coordinator.client.port}/state"
            ),
        )
