"""Notify entity: use a PiPup TV as a standard notify target.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from homeassistant.components.notify import NotifyEntity, NotifyEntityFeature
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from .api import PiPupError
from .const import ATTR_MESSAGE, ATTR_TITLE
from .coordinator import PiPupCoordinator
from .entity import PiPupEntity
from .services import build_device_payload


async def async_setup_entry(
    hass: HomeAssistant,
    entry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the notify entity."""
    coordinator: PiPupCoordinator = entry.runtime_data
    async_add_entities([PiPupNotifyEntity(coordinator, entry)])


class PiPupNotifyEntity(PiPupEntity, NotifyEntity):
    """Plain notify target (notify.send_message).

    Text-only popups honoring the per-device defaults (position, duration,
    colors); use the pipup.show action for media, camera streams and TTS.
    """

    _attr_translation_key = "notify"
    _attr_supported_features = NotifyEntityFeature.TITLE

    def __init__(self, coordinator: PiPupCoordinator, entry) -> None:
        """Initialize the notify entity."""
        super().__init__(coordinator, entry, "notify")

    async def async_send_message(self, message: str, title: str | None = None) -> None:
        """Show the message as a popup."""
        data = {ATTR_MESSAGE: message}
        if title:
            data[ATTR_TITLE] = title
        payload = build_device_payload(
            data, dict(self.coordinator.config_entry.options), None
        )
        try:
            await self.coordinator.client.notify(payload)
        except PiPupError as err:
            raise HomeAssistantError(str(err)) from err
        await self.coordinator.async_refresh_soon()
