"""Select: default popup position per device.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from homeassistant.components.select import SelectEntity
from homeassistant.const import EntityCategory
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from .const import CONF_DEFAULT_POSITION, DEFAULT_POSITION, POSITIONS
from .coordinator import PiPupCoordinator
from .entity import PiPupEntity


async def async_setup_entry(
    hass: HomeAssistant,
    entry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the default-position select."""
    coordinator: PiPupCoordinator = entry.runtime_data
    async_add_entities([PiPupDefaultPositionSelect(coordinator, entry)])


class PiPupDefaultPositionSelect(PiPupEntity, SelectEntity):
    """Default position used by pipup.show when no position is given.

    Stored in the config entry options so it survives restarts; the
    show action reads it at call time.
    """

    _attr_translation_key = "default_position"
    _attr_entity_category = EntityCategory.CONFIG
    _attr_options = list(POSITIONS)

    def __init__(self, coordinator: PiPupCoordinator, entry) -> None:
        """Initialize the select."""
        super().__init__(coordinator, entry, "default_position")
        self._entry = entry

    @property
    def current_option(self) -> str:
        """Return the configured default position."""
        return self._entry.options.get(CONF_DEFAULT_POSITION, DEFAULT_POSITION)

    async def async_select_option(self, option: str) -> None:
        """Store the new default in the config entry options."""
        self.hass.config_entries.async_update_entry(
            self._entry,
            options={**self._entry.options, CONF_DEFAULT_POSITION: option},
        )
        self.async_write_ha_state()
