"""Sensors: current popup, popups shown counter, app uptime.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from typing import Any

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntity,
    SensorStateClass,
)
from homeassistant.const import EntityCategory, UnitOfTime
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .coordinator import PiPupCoordinator
from .entity import PiPupEntity


async def async_setup_entry(
    hass: HomeAssistant,
    entry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the PiPup sensors."""
    coordinator: PiPupCoordinator = entry.runtime_data
    entities: list[CoordinatorEntity] = [PiPupCurrentPopupSensor(coordinator, entry)]
    # Fields below need the fork app >= 0.2.3; add only when the app reports them.
    if "popupsShown" in coordinator.data:
        entities.append(PiPupPopupsShownSensor(coordinator, entry))
    if "uptime" in coordinator.data:
        entities.append(PiPupUptimeSensor(coordinator, entry))
    async_add_entities(entities)


class PiPupCurrentPopupSensor(PiPupEntity, SensorEntity):
    """Shows the id of the currently visible popup."""

    _attr_translation_key = "current_popup"

    def __init__(self, coordinator: PiPupCoordinator, entry) -> None:
        """Initialize the sensor."""
        super().__init__(coordinator, entry, "current_popup")

    @property
    def native_value(self) -> str | None:
        """Return the popup id, 'naamloos' for id-less popups, or None."""
        if not self.coordinator.data.get("visible"):
            return None
        popup = self.coordinator.data.get("popup") or {}
        return popup.get("id") or "naamloos"

    @property
    def extra_state_attributes(self) -> dict[str, Any] | None:
        """Expose popup details."""
        popup = self.coordinator.data.get("popup")
        if not popup:
            return None
        return {
            "duration": popup.get("duration"),
            "indefinite": popup.get("indefinite"),
            "elapsed": popup.get("elapsed"),
        }


class PiPupPopupsShownSensor(PiPupEntity, SensorEntity):
    """Number of popups shown since the app started."""

    _attr_translation_key = "popups_shown"
    _attr_state_class = SensorStateClass.TOTAL_INCREASING

    def __init__(self, coordinator: PiPupCoordinator, entry) -> None:
        """Initialize the sensor."""
        super().__init__(coordinator, entry, "popups_shown")

    @property
    def native_value(self) -> int | None:
        """Return the counter."""
        return self.coordinator.data.get("popupsShown")


class PiPupUptimeSensor(PiPupEntity, SensorEntity):
    """App/service uptime in seconds (diagnostic)."""

    _attr_translation_key = "uptime"
    _attr_device_class = SensorDeviceClass.DURATION
    _attr_native_unit_of_measurement = UnitOfTime.SECONDS
    _attr_entity_category = EntityCategory.DIAGNOSTIC
    _attr_suggested_display_precision = 0

    def __init__(self, coordinator: PiPupCoordinator, entry) -> None:
        """Initialize the sensor."""
        super().__init__(coordinator, entry, "uptime")

    @property
    def native_value(self) -> int | None:
        """Return the uptime in seconds."""
        return self.coordinator.data.get("uptime")
