"""Actions (services) for the PiPup integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
from typing import Any

import voluptuous as vol

from homeassistant.config_entries import ConfigEntryState
from homeassistant.core import HomeAssistant, ServiceCall
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers import config_validation as cv
from homeassistant.helpers.network import get_url
from homeassistant.helpers.service import async_extract_config_entry_ids

from .api import PiPupError
from .const import (
    ATTR_BACKGROUND_COLOR,
    ATTR_CAMERA_ENTITY,
    ATTR_CAMERA_MODE,
    CONF_DEFAULT_POSITION,
    DEFAULT_POSITION,
    ATTR_DURATION,
    ATTR_IMAGE_URL,
    ATTR_MEDIA_HEIGHT,
    ATTR_MEDIA_WIDTH,
    ATTR_MESSAGE,
    ATTR_MESSAGE_COLOR,
    ATTR_MUTED,
    ATTR_MESSAGE_SIZE,
    ATTR_POPUP_ID,
    ATTR_POSITION,
    ATTR_TITLE,
    ATTR_TITLE_COLOR,
    ATTR_TITLE_SIZE,
    ATTR_VIDEO_URL,
    ATTR_WEB_URL,
    CAMERA_MODE_SNAPSHOT,
    CAMERA_MODE_STREAM,
    DOMAIN,
    POSITIONS,
    SERVICE_DISMISS,
    SERVICE_SHOW,
)

_LOGGER = logging.getLogger(__name__)

COLOR_REGEX = r"^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$|^#[0-9a-fA-F]{8}$"

SHOW_SCHEMA = vol.Schema(
    {
        vol.Optional(ATTR_TITLE): cv.string,
        vol.Optional(ATTR_MESSAGE): cv.string,
        vol.Optional(ATTR_DURATION, default=30): vol.All(
            vol.Coerce(int), vol.Range(min=0, max=86400)
        ),
        vol.Optional(ATTR_POPUP_ID): vol.All(
            cv.string, vol.Match(r"^[a-zA-Z0-9_-]{1,64}$")
        ),
        vol.Optional(ATTR_POSITION): vol.In(POSITIONS),
        vol.Optional(ATTR_TITLE_COLOR): vol.Match(COLOR_REGEX),
        vol.Optional(ATTR_TITLE_SIZE): vol.Coerce(float),
        vol.Optional(ATTR_MESSAGE_COLOR): vol.Match(COLOR_REGEX),
        vol.Optional(ATTR_MESSAGE_SIZE): vol.Coerce(float),
        vol.Optional(ATTR_BACKGROUND_COLOR): vol.Match(COLOR_REGEX),
        vol.Optional(ATTR_IMAGE_URL): cv.string,
        vol.Optional(ATTR_VIDEO_URL): cv.string,
        vol.Optional(ATTR_WEB_URL): cv.string,
        vol.Optional(ATTR_MEDIA_WIDTH): vol.All(
            vol.Coerce(int), vol.Range(min=1, max=3840)
        ),
        vol.Optional(ATTR_MEDIA_HEIGHT): vol.All(
            vol.Coerce(int), vol.Range(min=1, max=2160)
        ),
        vol.Optional(ATTR_MUTED, default=True): cv.boolean,
        vol.Optional(ATTR_CAMERA_ENTITY): cv.entity_id,
        vol.Optional(ATTR_CAMERA_MODE, default=CAMERA_MODE_STREAM): vol.In(
            [CAMERA_MODE_STREAM, CAMERA_MODE_SNAPSHOT]
        ),
    },
    extra=vol.ALLOW_EXTRA,  # allow target fields (device_id etc.)
)

DISMISS_SCHEMA = vol.Schema(
    {
        vol.Optional(ATTR_POPUP_ID): vol.All(
            cv.string, vol.Match(r"^[a-zA-Z0-9_-]{1,64}$")
        ),
    },
    extra=vol.ALLOW_EXTRA,
)


async def _coordinators_for_call(hass: HomeAssistant, call: ServiceCall) -> list:
    """Resolve targeted devices to loaded PiPup coordinators."""
    entry_ids = await async_extract_config_entry_ids(call)
    coordinators = []
    for entry_id in entry_ids:
        entry = hass.config_entries.async_get_entry(entry_id)
        if (
            entry is not None
            and entry.domain == DOMAIN
            and entry.state is ConfigEntryState.LOADED
        ):
            coordinators.append(entry.runtime_data)
    if not coordinators:
        raise HomeAssistantError(
            "No loaded PiPup devices in the action target; "
            "target a PiPup device (device_id)."
        )
    return coordinators


def _build_media(
    hass: HomeAssistant, data: dict[str, Any]
) -> dict[str, Any] | None:
    """Build the PiPup media payload from action data (URL variants)."""
    width = data.get(ATTR_MEDIA_WIDTH, 640)
    height = data.get(ATTR_MEDIA_HEIGHT, 360)
    muted = data.get(ATTR_MUTED, True)

    if url := data.get(ATTR_WEB_URL):
        return {"web": {"uri": url, "width": width, "height": height, "muted": muted}}
    if url := data.get(ATTR_VIDEO_URL):
        return {"video": {"uri": url, "width": width, "muted": muted}}
    if url := data.get(ATTR_IMAGE_URL):
        return {"image": {"uri": url, "width": width}}
    return None


async def _camera_media(
    hass: HomeAssistant, data: dict[str, Any]
) -> dict[str, Any] | bytes:
    """Resolve a camera entity to a stream URL payload or snapshot bytes."""
    # Imported here so the camera/stream components stay optional.
    from homeassistant.components.camera import (  # noqa: PLC0415
        async_get_image,
        async_request_stream,
    )

    entity_id = data[ATTR_CAMERA_ENTITY]
    mode = data.get(ATTR_CAMERA_MODE, CAMERA_MODE_STREAM)

    if mode == CAMERA_MODE_SNAPSHOT:
        image = await async_get_image(hass, entity_id)
        return image.content

    stream_path = await async_request_stream(hass, entity_id, "hls")
    base_url = get_url(hass, allow_external=False, prefer_external=False)
    width = data.get(ATTR_MEDIA_WIDTH, 640)
    muted = data.get(ATTR_MUTED, True)
    return {"video": {"uri": f"{base_url}{stream_path}", "width": width, "muted": muted}}


async def async_setup_services(hass: HomeAssistant) -> None:
    """Register the pipup.show and pipup.dismiss actions."""

    async def handle_show(call: ServiceCall) -> None:
        coordinators = await _coordinators_for_call(hass, call)
        data = call.data

        payload: dict[str, Any] = {
            "duration": data[ATTR_DURATION],
        }
        if popup_id := data.get(ATTR_POPUP_ID):
            payload["id"] = popup_id
        if title := data.get(ATTR_TITLE):
            payload["title"] = title
        if message := data.get(ATTR_MESSAGE):
            payload["message"] = message
        if color := data.get(ATTR_TITLE_COLOR):
            payload["titleColor"] = color
        if size := data.get(ATTR_TITLE_SIZE):
            payload["titleSize"] = size
        if color := data.get(ATTR_MESSAGE_COLOR):
            payload["messageColor"] = color
        if size := data.get(ATTR_MESSAGE_SIZE):
            payload["messageSize"] = size
        if color := data.get(ATTR_BACKGROUND_COLOR):
            payload["backgroundColor"] = color

        snapshot: bytes | None = None
        if data.get(ATTR_CAMERA_ENTITY):
            media = await _camera_media(hass, data)
            if isinstance(media, bytes):
                snapshot = media
            else:
                payload["media"] = media
        elif media := _build_media(hass, data):
            payload["media"] = media

        errors: list[str] = []
        for coordinator in coordinators:
            # position: explicit in the call, else the device's configured
            # default (select entity / config entry options)
            position = data.get(ATTR_POSITION) or coordinator.config_entry.options.get(
                CONF_DEFAULT_POSITION, DEFAULT_POSITION
            )
            device_payload = {**payload, "position": POSITIONS[position]}
            try:
                if snapshot is not None:
                    fields = {
                        key: str(value)
                        for key, value in device_payload.items()
                        if key != "media"
                    }
                    if width := data.get(ATTR_MEDIA_WIDTH):
                        fields["imageWidth"] = str(width)
                    await coordinator.client.notify_image(fields, snapshot)
                else:
                    await coordinator.client.notify(device_payload)
                await coordinator.async_refresh_soon()
            except PiPupError as err:
                errors.append(str(err))

        if errors:
            raise HomeAssistantError("; ".join(errors))

    async def handle_dismiss(call: ServiceCall) -> None:
        coordinators = await _coordinators_for_call(hass, call)
        popup_id = call.data.get(ATTR_POPUP_ID)

        errors: list[str] = []
        for coordinator in coordinators:
            try:
                await coordinator.client.cancel(popup_id)
                await coordinator.async_refresh_soon()
            except PiPupError as err:
                errors.append(str(err))

        if errors:
            raise HomeAssistantError("; ".join(errors))

    hass.services.async_register(
        DOMAIN, SERVICE_SHOW, handle_show, schema=SHOW_SCHEMA
    )
    hass.services.async_register(
        DOMAIN, SERVICE_DISMISS, handle_dismiss, schema=DISMISS_SCHEMA
    )
