"""Actions (services) for the PiPup integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
from typing import Any

import voluptuous as vol

from homeassistant.components import webhook as webhook_component
from homeassistant.config_entries import ConfigEntryState
from homeassistant.core import HomeAssistant, ServiceCall
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers import config_validation as cv
from homeassistant.helpers.network import get_url
from homeassistant.helpers.service import async_extract_config_entry_ids

from .api import PiPupError
from .const import (
    ATTR_BACKGROUND_COLOR,
    ATTR_BUTTONS,
    ATTR_CAMERA_ENTITY,
    ATTR_CAMERA_MODE,
    ATTR_DURATION,
    ATTR_IMAGE_URL,
    ATTR_MEDIA_HEIGHT,
    ATTR_MEDIA_WIDTH,
    ATTR_MESSAGE,
    ATTR_MESSAGE_COLOR,
    ATTR_MESSAGE_SIZE,
    ATTR_MUTED,
    ATTR_POPUP_ID,
    ATTR_POSITION,
    ATTR_SHOW_PROGRESS,
    ATTR_TITLE,
    ATTR_TITLE_COLOR,
    ATTR_TITLE_SIZE,
    ATTR_TTS,
    ATTR_TTS_LANGUAGE,
    ATTR_URGENCY,
    ATTR_VIDEO_URL,
    ATTR_WEB_URL,
    CAMERA_MODE_MJPEG,
    CAMERA_MODE_SNAPSHOT,
    CAMERA_MODE_STREAM,
    CONF_DEFAULT_BACKGROUND_COLOR,
    CONF_DEFAULT_DURATION,
    CONF_DEFAULT_MEDIA_HEIGHT,
    CONF_DEFAULT_MEDIA_WIDTH,
    CONF_DEFAULT_MESSAGE_COLOR,
    CONF_DEFAULT_MESSAGE_SIZE,
    CONF_DEFAULT_MUTED,
    CONF_DEFAULT_POSITION,
    CONF_DEFAULT_TITLE_COLOR,
    CONF_DEFAULT_TITLE_SIZE,
    DEFAULT_POSITION,
    DOMAIN,
    EVENT_BUTTON,
    POSITIONS,
    SERVICE_DISMISS,
    SERVICE_SHOW,
    URGENCIES,
    WEBHOOK_ID,
)

_LOGGER = logging.getLogger(__name__)

COLOR_REGEX = r"^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$|^#[0-9a-fA-F]{8}$"

# NB: geen schema-defaults voor duration/position/muted e.d. — een niet
# meegegeven veld valt terug op de per-apparaat default (options flow).
SHOW_SCHEMA = vol.Schema(
    {
        vol.Optional(ATTR_TITLE): cv.string,
        vol.Optional(ATTR_MESSAGE): cv.string,
        vol.Optional(ATTR_DURATION): vol.All(
            vol.Coerce(int), vol.Range(min=0, max=86400)
        ),
        vol.Optional(ATTR_POPUP_ID): vol.All(
            cv.string, vol.Match(r"^[a-zA-Z0-9_-]{1,64}$")
        ),
        vol.Optional(ATTR_POSITION): vol.In(POSITIONS),
        vol.Optional(ATTR_TITLE_COLOR): vol.Match(COLOR_REGEX),
        vol.Optional(ATTR_TITLE_SIZE): vol.Coerce(float),
        vol.Optional(ATTR_MESSAGE_COLOR): vol.Match(COLOR_REGEX),
        vol.Optional(ATTR_MESSAGE_SIZE): vol.Coerce(float),
        vol.Optional(ATTR_BACKGROUND_COLOR): vol.Match(COLOR_REGEX),
        vol.Optional(ATTR_IMAGE_URL): cv.string,
        vol.Optional(ATTR_VIDEO_URL): cv.string,
        vol.Optional(ATTR_WEB_URL): cv.string,
        vol.Optional(ATTR_MEDIA_WIDTH): vol.All(
            vol.Coerce(int), vol.Range(min=1, max=3840)
        ),
        vol.Optional(ATTR_MEDIA_HEIGHT): vol.All(
            vol.Coerce(int), vol.Range(min=1, max=2160)
        ),
        vol.Optional(ATTR_MUTED): cv.boolean,
        vol.Optional(ATTR_TTS): cv.string,
        vol.Optional(ATTR_TTS_LANGUAGE): cv.string,
        vol.Optional(ATTR_URGENCY): vol.In(URGENCIES),
        vol.Optional(ATTR_SHOW_PROGRESS): cv.boolean,
        vol.Optional(ATTR_BUTTONS): vol.All(
            cv.ensure_list,
            [
                vol.Schema(
                    {
                        vol.Required("id"): vol.All(
                            cv.string, vol.Match(r"^[a-zA-Z0-9_-]{1,32}$")
                        ),
                        vol.Required("label"): cv.string,
                    }
                )
            ],
            vol.Length(min=1, max=3),
        ),
        vol.Optional(ATTR_CAMERA_ENTITY): cv.entity_id,
        vol.Optional(ATTR_CAMERA_MODE, default=CAMERA_MODE_MJPEG): vol.In(
            [CAMERA_MODE_MJPEG, CAMERA_MODE_STREAM, CAMERA_MODE_SNAPSHOT]
        ),
    },
    extra=vol.ALLOW_EXTRA,  # allow target fields (device_id etc.)
)

DISMISS_SCHEMA = vol.Schema(
    {
        vol.Optional(ATTR_POPUP_ID): vol.All(
            cv.string, vol.Match(r"^[a-zA-Z0-9_-]{1,64}$")
        ),
    },
    extra=vol.ALLOW_EXTRA,
)


async def _coordinators_for_call(hass: HomeAssistant, call: ServiceCall) -> list:
    """Resolve targeted devices to loaded PiPup coordinators."""
    entry_ids = await async_extract_config_entry_ids(call)
    coordinators = []
    for entry_id in entry_ids:
        entry = hass.config_entries.async_get_entry(entry_id)
        if (
            entry is not None
            and entry.domain == DOMAIN
            and entry.state is ConfigEntryState.LOADED
        ):
            coordinators.append(entry.runtime_data)
    if not coordinators:
        raise HomeAssistantError(
            "No loaded PiPup devices in the action target; "
            "target a PiPup device (device_id)."
        )
    return coordinators


def _device_payload(
    data: dict[str, Any],
    opts: dict[str, Any],
    stream_uri: str | None,
    web_uri: str | None = None,
    callback_url: str | None = None,
) -> dict[str, Any]:
    """Build the notify payload for one device.

    Every field falls back to the device's configured default (options
    flow) when not given in the action call.
    """

    def pick(attr: str, conf: str, fallback: Any) -> Any:
        if attr in data:
            return data[attr]
        value = opts.get(conf)
        # 0 / "" mean "not configured" for sizes and colors
        return value if value not in (None, 0, 0.0, "") else fallback

    payload: dict[str, Any] = {
        "duration": pick(ATTR_DURATION, CONF_DEFAULT_DURATION, 30),
        "position": POSITIONS[
            data.get(ATTR_POSITION)
            or opts.get(CONF_DEFAULT_POSITION, DEFAULT_POSITION)
        ],
    }
    if popup_id := data.get(ATTR_POPUP_ID):
        payload["id"] = popup_id
    if title := data.get(ATTR_TITLE):
        payload["title"] = title
    if message := data.get(ATTR_MESSAGE):
        payload["message"] = message
    if tts := data.get(ATTR_TTS):
        payload["tts"] = tts  # spoken on the device (app >= 0.2.5)
        if language := data.get(ATTR_TTS_LANGUAGE):
            payload["ttsLanguage"] = language

    # app >= 0.3.0
    if urgency := data.get(ATTR_URGENCY):
        payload["urgency"] = urgency
    if data.get(ATTR_SHOW_PROGRESS):
        payload["showProgress"] = True
    if buttons := data.get(ATTR_BUTTONS):
        payload["buttons"] = buttons
        if callback_url:
            payload["callback"] = callback_url

    if color := pick(ATTR_TITLE_COLOR, CONF_DEFAULT_TITLE_COLOR, None):
        payload["titleColor"] = color
    if size := pick(ATTR_TITLE_SIZE, CONF_DEFAULT_TITLE_SIZE, None):
        payload["titleSize"] = size
    if color := pick(ATTR_MESSAGE_COLOR, CONF_DEFAULT_MESSAGE_COLOR, None):
        payload["messageColor"] = color
    if size := pick(ATTR_MESSAGE_SIZE, CONF_DEFAULT_MESSAGE_SIZE, None):
        payload["messageSize"] = size
    if color := pick(ATTR_BACKGROUND_COLOR, CONF_DEFAULT_BACKGROUND_COLOR, None):
        payload["backgroundColor"] = color

    width = pick(ATTR_MEDIA_WIDTH, CONF_DEFAULT_MEDIA_WIDTH, 640)
    height = pick(ATTR_MEDIA_HEIGHT, CONF_DEFAULT_MEDIA_HEIGHT, 360)
    muted = data.get(ATTR_MUTED, opts.get(CONF_DEFAULT_MUTED, True))

    if stream_uri:
        payload["media"] = {"video": {"uri": stream_uri, "width": width, "muted": muted}}
    elif web_uri:
        payload["media"] = {
            "web": {"uri": web_uri, "width": width, "height": height, "muted": muted}
        }
    elif url := data.get(ATTR_WEB_URL):
        payload["media"] = {
            "web": {"uri": url, "width": width, "height": height, "muted": muted}
        }
    elif url := data.get(ATTR_VIDEO_URL):
        payload["media"] = {"video": {"uri": url, "width": width, "muted": muted}}
    elif url := data.get(ATTR_IMAGE_URL):
        payload["media"] = {"image": {"uri": url, "width": width}}

    return payload


async def _camera_media(
    hass: HomeAssistant, data: dict[str, Any]
) -> tuple[str | None, str | None, bytes | None]:
    """Resolve a camera entity to (video_uri, web_uri, snapshot_bytes).

    Default is MJPEG via HA's camera proxy (rendered in the popup's web
    view): software-decoded and audio-free, so it cannot stall live-TV
    playback on the device. 'stream' (HLS) uses a hardware decoder via
    VideoView and is known to freeze concurrent video on some TVs.
    """
    # Imported here so the camera/stream components stay optional.
    from homeassistant.components.camera import (  # noqa: PLC0415
        async_get_image,
        async_request_stream,
    )

    entity_id = data[ATTR_CAMERA_ENTITY]
    mode = data.get(ATTR_CAMERA_MODE, CAMERA_MODE_MJPEG)
    base_url = get_url(hass, allow_external=False, prefer_external=False)

    if mode == CAMERA_MODE_SNAPSHOT:
        image = await async_get_image(hass, entity_id)
        return None, None, image.content

    if mode == CAMERA_MODE_MJPEG:
        from datetime import timedelta  # noqa: PLC0415

        from homeassistant.components.http.auth import (  # noqa: PLC0415
            async_sign_path,
        )

        signed = async_sign_path(
            hass,
            f"/api/camera_proxy_stream/{entity_id}",
            timedelta(hours=24),
        )
        return None, f"{base_url}{signed}", None

    stream_path = await async_request_stream(hass, entity_id, "hls")
    return f"{base_url}{stream_path}", None, None


async def _handle_button_webhook(hass: HomeAssistant, webhook_id: str, request) -> None:
    """Fire a pipup_button event for a button press POSTed by the app."""
    try:
        data = await request.json()
    except ValueError:
        _LOGGER.warning("Invalid JSON on %s webhook", webhook_id)
        return
    _LOGGER.debug("Popup button pressed: %s", data)
    hass.bus.async_fire(
        EVENT_BUTTON,
        {
            "popup_id": data.get("popup"),
            "button": data.get("button"),
            "label": data.get("label"),
            "device_id": data.get("device"),
            "device_name": data.get("name"),
        },
    )


async def async_setup_services(hass: HomeAssistant) -> None:
    """Register the pipup.show/pipup.dismiss actions and the button webhook."""

    try:
        webhook_component.async_register(
            hass,
            DOMAIN,
            "PiPup buttons",
            WEBHOOK_ID,
            _handle_button_webhook,
            local_only=True,
            allowed_methods=["POST"],
        )
    except ValueError:
        _LOGGER.debug("Webhook %s already registered", WEBHOOK_ID)

    async def handle_show(call: ServiceCall) -> None:
        coordinators = await _coordinators_for_call(hass, call)
        data = call.data

        stream_uri: str | None = None
        web_uri: str | None = None
        snapshot: bytes | None = None
        if data.get(ATTR_CAMERA_ENTITY):
            stream_uri, web_uri, snapshot = await _camera_media(hass, data)

        callback_url: str | None = None
        if data.get(ATTR_BUTTONS):
            base_url = get_url(hass, allow_external=False, prefer_external=False)
            callback_url = f"{base_url}/api/webhook/{WEBHOOK_ID}"

        errors: list[str] = []
        for coordinator in coordinators:
            opts = dict(coordinator.config_entry.options)
            payload = _device_payload(data, opts, stream_uri, web_uri, callback_url)
            try:
                if snapshot is not None:
                    fields = {
                        key: str(value)
                        for key, value in payload.items()
                        if key != "media"
                    }
                    fields["imageWidth"] = str(
                        payload.get("media", {}).get("image", {}).get("width")
                        or data.get(ATTR_MEDIA_WIDTH)
                        or opts.get(CONF_DEFAULT_MEDIA_WIDTH)
                        or 640
                    )
                    await coordinator.client.notify_image(fields, snapshot)
                else:
                    await coordinator.client.notify(payload)
                await coordinator.async_refresh_soon()
            except PiPupError as err:
                errors.append(str(err))

        if errors:
            raise HomeAssistantError("; ".join(errors))

    async def handle_dismiss(call: ServiceCall) -> None:
        coordinators = await _coordinators_for_call(hass, call)
        popup_id = call.data.get(ATTR_POPUP_ID)

        errors: list[str] = []
        for coordinator in coordinators:
            try:
                await coordinator.client.cancel(popup_id)
                await coordinator.async_refresh_soon()
            except PiPupError as err:
                errors.append(str(err))

        if errors:
            raise HomeAssistantError("; ".join(errors))

    hass.services.async_register(
        DOMAIN, SERVICE_SHOW, handle_show, schema=SHOW_SCHEMA
    )
    hass.services.async_register(
        DOMAIN, SERVICE_DISMISS, handle_dismiss, schema=DISMISS_SCHEMA
    )
