"""Update entity: compare installed app version with the latest GitHub release.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
from datetime import timedelta

import aiohttp
from awesomeversion import AwesomeVersion

from homeassistant.components.update import UpdateEntity, UpdateEntityFeature
from homeassistant.core import HomeAssistant
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.util import dt as dt_util

from .api import PiPupError
from .const import DOMAIN
from .coordinator import PiPupCoordinator
from .entity import PiPupEntity

_LOGGER = logging.getLogger(__name__)

# GitHub releases of the PiPup fork; polled sparingly (anonymous rate limit).
RELEASES_URL = "https://api.github.com/repos/mhoogenbosch/PiPup/releases/latest"
RELEASE_PAGE = "https://github.com/mhoogenbosch/PiPup/releases"
# How often each entity re-reads the shared cache. Deliberately shorter than the
# cache TTL: a poll that finds a live cache entry costs nothing, so a short
# interval only means a refreshed tag reaches every TV quickly. Equal values
# would let an entity sit a full cycle behind a cache another entity refreshed.
SCAN_INTERVAL = timedelta(hours=1)
# One TV per config entry, but the latest release is the same for all of them —
# cache it process-wide so N TVs make one GitHub call per interval, not N.
_CACHE_KEY = "latest_release_cache"
_CACHE_TTL = timedelta(hours=6)
# How long the entity keeps reporting progress after our own install request when the
# device has not confirmed the new version yet. Matches the app's abandoned-install
# deadline; on Android < 12 this window is where someone confirms on the TV.
INSTALL_PROGRESS_DEADLINE = timedelta(minutes=15)


async def _latest_release_tag(hass: HomeAssistant, force: bool = False) -> str | None:
    """Return the latest fork release tag (without leading v), cached per TTL.

    `force` bypasses the cache — used when a device reports a version the cache
    does not know yet, which can only mean the cached value is out of date.
    """
    cache = hass.data.setdefault(DOMAIN, {}).get(_CACHE_KEY)
    now = dt_util.utcnow()
    if cache and not force and cache["expires"] > now:
        return cache["tag"]

    session = async_get_clientsession(hass)
    try:
        async with session.get(
            RELEASES_URL, timeout=aiohttp.ClientTimeout(total=15)
        ) as resp:
            if resp.status != 200:
                _LOGGER.debug("GitHub releases returned %s", resp.status)
                return cache["tag"] if cache else None
            data = await resp.json()
    except (aiohttp.ClientError, TimeoutError) as err:
        _LOGGER.debug("Could not fetch latest PiPup release: %s", err)
        return cache["tag"] if cache else None

    tag = (data.get("tag_name") or "").lstrip("v") or None
    hass.data[DOMAIN][_CACHE_KEY] = {"tag": tag, "expires": now + _CACHE_TTL}
    return tag


async def async_setup_entry(
    hass: HomeAssistant,
    entry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the update entity."""
    coordinator: PiPupCoordinator = entry.runtime_data
    async_add_entities([PiPupUpdateEntity(coordinator, entry)], update_before_add=True)


class PiPupUpdateEntity(PiPupEntity, UpdateEntity):
    """Shows when a newer PiPup fork APK is available."""

    _attr_translation_key = "app_update"
    _attr_release_url = RELEASE_PAGE

    def __init__(self, coordinator: PiPupCoordinator, entry) -> None:
        """Initialize the update entity."""
        super().__init__(coordinator, entry, "app_update")
        self._latest: str | None = None
        self._install_requested_at = None

    @property
    def should_poll(self) -> bool:
        """Poll, unlike the other entities on this coordinator.

        This has to be a property. CoordinatorEntity declares should_poll as a
        cached_property returning False — correct for entities whose data comes
        from the coordinator, but this one also has to reach GitHub, which the
        coordinator knows nothing about. A class-level `_attr_should_poll = True`
        loses to that property and is silently ignored, which is exactly what
        happened up to 1.8.1: async_update ran once at setup and never again, so
        latest_version froze at whatever it was when Home Assistant started.
        """
        return True

    @property
    def installed_version(self) -> str | None:
        """Version reported by the app on the TV."""
        return self.coordinator.data.get("version")

    @property
    def latest_version(self) -> str | None:
        """Latest release tag on GitHub (without leading v)."""
        return self._latest

    @property
    def supported_features(self) -> UpdateEntityFeature:
        """Offer Install only when the app can update itself (>= 0.6.0)."""
        if "update" in self.coordinator.data:
            return UpdateEntityFeature.INSTALL
        return UpdateEntityFeature(0)

    @property
    def in_progress(self) -> bool:
        """True while the TV is downloading/installing the update.

        The app's own `installing` flag alone misses the window in practice: on
        Android 12+ the whole install takes a few seconds and the coordinator polls
        every 15, so pressing Install showed no progress at all and the version just
        jumped later. After our own install request the entity therefore reports
        progress until the installed version actually changes (or a deadline passes -
        matching the app's 15-minute abandoned-install deadline).
        """
        if bool((self.coordinator.data.get("update") or {}).get("installing")):
            return True
        if self._install_requested_at is None:
            return False
        if dt_util.utcnow() - self._install_requested_at > INSTALL_PROGRESS_DEADLINE:
            self._install_requested_at = None
            return False
        installed = self.installed_version
        if installed and self._latest and installed == self._latest:
            self._install_requested_at = None  # it landed
            return False
        return True

    @property
    def extra_state_attributes(self) -> dict[str, str | bool | None]:
        """Expose why an install did not land.

        Field report: "the update failed" with nothing anywhere in HA saying why,
        while the app had the reason in /state all along. Three causes, all visible
        here: a missing install permission (an `adb install -r` resets it); Android
        < 12, where the system shows a confirmation dialog ON THE TV that someone has
        to accept with the remote (`requires_remote`); and `pending_confirmation`,
        which is true while an install is actually waiting for that press right now —
        the app wakes the TV and shows a popup with an Install button (app >= 0.12.1).
        """
        update = self.coordinator.data.get("update") or {}
        device = self.coordinator.data.get("device") or {}
        permissions = self.coordinator.data.get("permissions") or {}
        # `silent` is authoritative (app >= 0.12.1: false on Android < 12, where an
        # install cannot complete without a remote press); fall back to the OS version
        # for older apps that do not report it.
        silent = update.get("silent")
        if silent is not None:
            requires_remote = not silent
        else:
            android = str(device.get("android") or "")
            major = int(android.split(".")[0]) if android.split(".")[0].isdigit() else None
            requires_remote = major is not None and major < 12
        return {
            "install_error": update.get("error"),
            "install_permission": permissions.get("installPackages"),
            "requires_remote": requires_remote,
            "pending_confirmation": bool(update.get("pendingUserAction")),
        }

    async def async_install(self, version: str | None, backup: bool, **kwargs) -> None:
        """Trigger the app's self-update on the TV.

        On Android 12+ this completes silently; older devices show the system's
        install confirmation on screen, which has to be accepted with the remote.
        """
        try:
            await self.coordinator.client.update_app()
        except PiPupError as err:
            raise HomeAssistantError(str(err)) from err
        self._install_requested_at = dt_util.utcnow()
        self.async_write_ha_state()
        await self.coordinator.async_refresh_soon()

    async def async_update(self) -> None:
        """Refresh the latest release tag from the shared cache.

        A TV running a version the cache does not know about means the cache is
        stale (a release tagged inside the 6h TTL, or the app self-updated
        first) — refetch immediately so "latest" never lags behind "installed".
        """
        self._latest = await _latest_release_tag(self.hass)
        installed = self.installed_version
        if installed and self._latest and installed != self._latest:
            if AwesomeVersion(installed) > AwesomeVersion(self._latest):
                self._latest = await _latest_release_tag(self.hass, force=True)
