"""Update entity: compare installed app version with the latest GitHub release.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import asyncio
import logging
from datetime import timedelta

import aiohttp
from awesomeversion import AwesomeVersion, AwesomeVersionException

from homeassistant.components.update import UpdateEntity, UpdateEntityFeature
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.util import dt as dt_util

from homeassistant.helpers import entity_registry as er

from .api import PiPupError
from .const import (
    CONF_UPDATE_SOURCE,
    DEFAULT_UPDATE_SOURCE,
    DOMAIN,
    UPDATE_SOURCE_OFF,
)
from .coordinator import PiPupCoordinator
from .entity import PiPupEntity

_LOGGER = logging.getLogger(__name__)

# GitHub releases of the PiPup fork; polled sparingly (anonymous rate limit).
def _source_urls(source: str) -> tuple[str, str]:
    """(releases URL, release page) for an update source.

    ``github:<owner>/<repo>`` reads that repo's latest release; an http(s) folder URL
    reads ``<folder>/releases.json`` (GitHub's releases list, e.g. a LAN mirror).
    """
    if source.startswith("github:"):
        repo = source[len("github:"):]
        return (
            f"https://api.github.com/repos/{repo}/releases/latest",
            f"https://github.com/{repo}/releases",
        )
    folder = source.rstrip("/")
    return f"{folder}/releases.json", f"{folder}/"
# How often each entity re-reads the shared cache. Deliberately shorter than the
# cache TTL: a poll that finds a live cache entry costs nothing, so a short
# interval only means a refreshed tag reaches every TV quickly. Equal values
# would let an entity sit a full cycle behind a cache another entity refreshed.
SCAN_INTERVAL = timedelta(hours=1)
# One TV per config entry, but the latest release is the same for all of them —
# cache it process-wide so N TVs make one GitHub call per interval, not N.
_CACHE_KEY = "latest_release_cache"
_CACHE_TTL = timedelta(hours=6)
# A failed fetch (rate limit, no internet) is remembered too, briefly, so every
# entity's poll does not hit the source again right away.
_FAILURE_TTL = timedelta(minutes=15)
# one fetch per source at a time: N TVs starting together make one call, not N
_LOCK_KEY = "latest_release_locks"
# How long the entity keeps reporting progress after our own install request when the
# device has not confirmed the new version yet. Matches the app's abandoned-install
# deadline; on Android < 12 this window is where someone confirms on the TV.
INSTALL_PROGRESS_DEADLINE = timedelta(minutes=15)


async def _latest_release_tag(
    hass: HomeAssistant, source: str, force: bool = False
) -> str | None:
    """Return the latest release tag (without leading v) of a source, cached per TTL.

    `force` bypasses the cache — used when a device reports a version the cache
    does not know yet, which can only mean the cached value is out of date.
    """
    domain_data = hass.data.setdefault(DOMAIN, {})
    caches = domain_data.setdefault(_CACHE_KEY, {})
    lock = domain_data.setdefault(_LOCK_KEY, {}).setdefault(source, asyncio.Lock())
    async with lock:
        # checked under the lock: whoever held it may just have filled the cache
        cache = caches.get(source)
        now = dt_util.utcnow()
        if cache and not force and cache["expires"] > now:
            return cache["tag"]
        return await _fetch_release_tag(hass, source, caches, cache, now)


async def _fetch_release_tag(
    hass: HomeAssistant,
    source: str,
    caches: dict,
    cache: dict | None,
    now,
) -> str | None:
    """Fetch the tag from the source and cache it; keep the known tag on failure."""
    known = cache["tag"] if cache else None
    session = async_get_clientsession(hass)
    try:
        async with session.get(
            _source_urls(source)[0], timeout=aiohttp.ClientTimeout(total=15)
        ) as resp:
            if resp.status != 200:
                _LOGGER.debug("GitHub releases returned %s", resp.status)
                caches[source] = {"tag": known, "expires": now + _FAILURE_TTL}
                return known
            data = await resp.json()
    except (aiohttp.ClientError, TimeoutError) as err:
        _LOGGER.debug("Could not fetch latest PiPup release: %s", err)
        caches[source] = {"tag": known, "expires": now + _FAILURE_TTL}
        return known

    if isinstance(data, list):
        # a folder's releases.json is the list: same pick as the app (first release
        # that is neither draft nor prerelease)
        data = next(
            (r for r in data if not r.get("draft") and not r.get("prerelease")), {}
        )
    tag = (data.get("tag_name") or "").lstrip("v") or None
    caches[source] = {"tag": tag, "expires": now + _CACHE_TTL}
    return tag


async def async_setup_entry(
    hass: HomeAssistant,
    entry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up the update entity."""
    coordinator: PiPupCoordinator = entry.runtime_data
    source = entry.options.get(CONF_UPDATE_SOURCE) or DEFAULT_UPDATE_SOURCE
    if source == UPDATE_SOURCE_OFF:
        # off = no update checks at all, from HA or the TV: drop a leftover entity
        registry = er.async_get(hass)
        unique_id = f"{entry.unique_id or entry.entry_id}_app_update"
        if entity_id := registry.async_get_entity_id("update", DOMAIN, unique_id):
            registry.async_remove(entity_id)
        return
    async_add_entities(
        [PiPupUpdateEntity(coordinator, entry, source)], update_before_add=True
    )


class PiPupUpdateEntity(PiPupEntity, UpdateEntity):
    """Shows when a newer PiPup fork APK is available."""

    _attr_translation_key = "app_update"

    def __init__(self, coordinator: PiPupCoordinator, entry, source: str) -> None:
        """Initialize the update entity."""
        super().__init__(coordinator, entry, "app_update")
        self._source = source
        self._attr_release_url = _source_urls(source)[1]
        self._latest: str | None = None
        self._install_requested_at = None
        # the version the TV ran when Install was pressed: any other version = landed
        self._version_at_install: str | None = None

    @property
    def should_poll(self) -> bool:
        """Poll, unlike the other entities on this coordinator.

        This has to be a property. CoordinatorEntity declares should_poll as a
        cached_property returning False — correct for entities whose data comes
        from the coordinator, but this one also has to reach GitHub, which the
        coordinator knows nothing about. A class-level `_attr_should_poll = True`
        loses to that property and is silently ignored, which is exactly what
        happened up to 1.8.1: async_update ran once at setup and never again, so
        latest_version froze at whatever it was when Home Assistant started.
        """
        return True

    @property
    def installed_version(self) -> str | None:
        """Version reported by the app on the TV."""
        return self.coordinator.data.get("version")

    @property
    def latest_version(self) -> str | None:
        """Latest release tag on GitHub (without leading v)."""
        return self._latest

    @property
    def supported_features(self) -> UpdateEntityFeature:
        """Offer Install only when the app can update itself (>= 0.6.0).

        PROGRESS has to come with it: Home Assistant only reads `in_progress` from
        an entity that declares PROGRESS. Without it, it shows its own flag, which
        is only set while `async_install` runs - and that returns as soon as the TV
        has accepted the request. Up to 1.19.0 the Install button therefore came
        back after a few seconds while the TV was still downloading, and a second
        press failed with "an update is already running".
        """
        if "update" in self.coordinator.data:
            return UpdateEntityFeature.INSTALL | UpdateEntityFeature.PROGRESS
        return UpdateEntityFeature(0)

    @property
    def in_progress(self) -> bool:
        """True while the TV is downloading/installing the update.

        The app's own `installing` flag alone misses the window in practice: on
        Android 12+ the whole install takes a few seconds and the coordinator polls
        every 15, so pressing Install showed no progress at all and the version just
        jumped later. After our own install request the entity therefore reports
        progress until the installed version actually changes (or a deadline passes -
        matching the app's 15-minute abandoned-install deadline).
        """
        if bool((self.coordinator.data.get("update") or {}).get("installing")):
            return True
        if self._install_requested_at is None:
            return False
        if dt_util.utcnow() - self._install_requested_at > INSTALL_PROGRESS_DEADLINE:
            self._install_requested_at = None
            return False
        installed = self.installed_version
        if installed and (
            (self._latest and installed == self._latest)
            # also without a known latest tag (source unreachable, rate limited):
            # the TV now runs another version than when Install was pressed
            or installed != self._version_at_install
        ):
            self._install_requested_at = None  # it landed
            return False
        return True

    @property
    def update_percentage(self) -> int | None:
        """Download progress reported by the app (>= 0.23.0) while it downloads.

        None in every other phase (installing, waiting for the remote press) and on
        older apps: Home Assistant then shows an indeterminate progress indicator.
        """
        if not self.coordinator.online:
            # The app restarts itself to finish the install. The coordinator then
            # returns its previous data instead of failing (so last_update_success
            # stays true - 1.20.0 checked that and never caught this), which would
            # freeze the bar at the last percentage it saw.
            return None
        progress = (self.coordinator.data.get("update") or {}).get("progress")
        if isinstance(progress, int) and not isinstance(progress, bool):
            return max(0, min(100, progress))
        return None

    @callback
    def _handle_coordinator_update(self) -> None:
        """Poll fast while an update runs, so the percentage moves; normal otherwise."""
        self.coordinator.set_update_polling(self.in_progress)
        super()._handle_coordinator_update()

    @property
    def extra_state_attributes(self) -> dict[str, str | bool | None]:
        """Expose why an install did not land.

        Field report: "the update failed" with nothing anywhere in HA saying why,
        while the app had the reason in /state all along. Three causes, all visible
        here: a missing install permission (an `adb install -r` resets it); Android
        < 12, where the system shows a confirmation dialog ON THE TV that someone has
        to accept with the remote (`requires_remote`); and `pending_confirmation`,
        which is true while an install is actually waiting for that press right now —
        the app wakes the TV and shows a popup with an Install button (app >= 0.12.1).
        """
        update = self.coordinator.data.get("update") or {}
        device = self.coordinator.data.get("device") or {}
        permissions = self.coordinator.data.get("permissions") or {}
        # `silent` is authoritative (app >= 0.12.1: false on Android < 12, where an
        # install cannot complete without a remote press); fall back to the OS version
        # for older apps that do not report it.
        silent = update.get("silent")
        if silent is not None:
            requires_remote = not silent
        else:
            android = str(device.get("android") or "")
            major = int(android.split(".")[0]) if android.split(".")[0].isdigit() else None
            requires_remote = major is not None and major < 12
        return {
            "install_error": update.get("error"),
            "install_permission": permissions.get("installPackages"),
            "requires_remote": requires_remote,
            "pending_confirmation": bool(update.get("pendingUserAction")),
        }

    async def async_install(self, version: str | None, backup: bool, **kwargs) -> None:
        """Trigger the app's self-update on the TV.

        On Android 12+ this completes silently; older devices show the system's
        install confirmation on screen, which has to be accepted with the remote.
        """
        if self.in_progress:
            # Normally unreachable from the UI (the button is disabled while
            # in_progress), but an action or automation can still call it.
            raise HomeAssistantError(
                "An update of the PiPup app is already running on this TV"
            )
        version_at_install = self.installed_version
        try:
            await self.coordinator.client.update_app()
        except PiPupError as err:
            raise HomeAssistantError(str(err)) from err
        self._version_at_install = version_at_install
        self._install_requested_at = dt_util.utcnow()
        self.coordinator.set_update_polling(True)
        self.async_write_ha_state()
        await self.coordinator.async_refresh_soon()

    async def async_update(self) -> None:
        """Refresh the latest release tag from the shared cache.

        A TV running a version the cache does not know about means the cache is
        stale (a release tagged inside the 6h TTL, or the app self-updated
        first) — refetch immediately so "latest" never lags behind "installed".
        """
        self._latest = await _latest_release_tag(self.hass, self._source)
        installed = self.installed_version
        if installed and self._latest and installed != self._latest:
            try:
                newer = AwesomeVersion(installed) > AwesomeVersion(self._latest)
            except AwesomeVersionException:
                # an unparseable version on either side: nothing to compare, keep the tag
                newer = False
            if newer:
                self._latest = await _latest_release_tag(self.hass, self._source, force=True)
